heuristic(trivandrum, trivandrum, 0).
heuristic(trivandrum, nagpur, 1428).
heuristic(trivandrum, varanasi, 1980).
heuristic(trivandrum, jamshedpur, 1876).
heuristic(trivandrum, agartala, 2292).
heuristic(trivandrum, vishakapatnam, 1229).
heuristic(trivandrum, asansol, 2002).
heuristic(trivandrum, gwalior, 1979).
heuristic(trivandrum, surat, 1483).
heuristic(trivandrum, ranchi, 1880).
heuristic(trivandrum, nasik, 1326).
heuristic(trivandrum, ahmedabad, 1687).
heuristic(trivandrum, madras, 624).
heuristic(trivandrum, calicut, 334).
heuristic(trivandrum, kolhapur, 960).
heuristic(trivandrum, amritsar, 2586).
heuristic(trivandrum, vijayawada, 979).
heuristic(trivandrum, bombay, 1258).
heuristic(trivandrum, hubli, 791).
heuristic(trivandrum, bhubaneshwar, 1625).
heuristic(trivandrum, chandigarh, 2477).
heuristic(trivandrum, agra, 2084).
heuristic(trivandrum, allahabad, 1957).
heuristic(trivandrum, jabalpur, 1666).
heuristic(trivandrum, hyderabad, 1005).
heuristic(trivandrum, shimla, 2518).
heuristic(trivandrum, pondicherry, 494).
heuristic(trivandrum, pune, 1166).
heuristic(trivandrum, kanpur, 2032).
heuristic(trivandrum, ludhiana, 2498).
heuristic(trivandrum, madurai, 205).
heuristic(trivandrum, shillong, 2476).
heuristic(trivandrum, calcutta, 1987).
heuristic(trivandrum, delhi, 2244).
heuristic(trivandrum, cochin, 180).
heuristic(trivandrum, lucknow, 2087).
heuristic(trivandrum, bangalore, 504).
heuristic(trivandrum, indore, 1589).
heuristic(trivandrum, patna, 2095).
heuristic(trivandrum, baroda, 1591).
heuristic(trivandrum, bhopal, 1646).
heuristic(trivandrum, meerut, 2284).
heuristic(trivandrum, coimbatore, 282).
heuristic(trivandrum, panjim, 851).
heuristic(trivandrum, jaipur, 2055).
heuristic(trivandrum, jullundur, 2547).
heuristic(trivandrum, imphal, 2561).
heuristic(nagpur, trivandrum, 1428).
heuristic(nagpur, nagpur, 0).
heuristic(nagpur, varanasi, 611).
heuristic(nagpur, jamshedpur, 757).
heuristic(nagpur, agartala, 1290).
heuristic(nagpur, vishakapatnam, 580).
heuristic(nagpur, asansol, 859).
heuristic(nagpur, gwalior, 572).
heuristic(nagpur, surat, 651).
heuristic(nagpur, ranchi, 686).
heuristic(nagpur, nasik, 567).
heuristic(nagpur, ahmedabad, 705).
heuristic(nagpur, madras, 909).
heuristic(nagpur, calicut, 1156).
heuristic(nagpur, kolhapur, 711).
heuristic(nagpur, amritsar, 1241).
heuristic(nagpur, vijayawada, 542).
heuristic(nagpur, bombay, 689).
heuristic(nagpur, hubli, 768).
heuristic(nagpur, bhubaneshwar, 708).
heuristic(nagpur, chandigarh, 1092).
heuristic(nagpur, agra, 680).
heuristic(nagpur, allahabad, 555).
heuristic(nagpur, jabalpur, 242).
heuristic(nagpur, hyderabad, 424).
heuristic(nagpur, shimla, 1125).
heuristic(nagpur, pondicherry, 1029).
heuristic(nagpur, pune, 621).
heuristic(nagpur, kanpur, 604).
heuristic(nagpur, ludhiana, 1133).
heuristic(nagpur, madurai, 1254).
heuristic(nagpur, shillong, 1398).
heuristic(nagpur, calcutta, 972).
heuristic(nagpur, delhi, 855).
heuristic(nagpur, cochin, 1283).
heuristic(nagpur, lucknow, 662).
heuristic(nagpur, bangalore, 924).
heuristic(nagpur, indore, 377).
heuristic(nagpur, patna, 793).
heuristic(nagpur, baroda, 625).
heuristic(nagpur, bhopal, 292).
heuristic(nagpur, meerut, 884).
heuristic(nagpur, coimbatore, 1151).
heuristic(nagpur, panjim, 840).
heuristic(nagpur, jaipur, 724).
heuristic(nagpur, jullundur, 1186).
heuristic(nagpur, imphal, 1576).
heuristic(varanasi, trivandrum, 1980).
heuristic(varanasi, nagpur, 611).
heuristic(varanasi, varanasi, 0).
heuristic(varanasi, jamshedpur, 431).
heuristic(varanasi, agartala, 858).
heuristic(varanasi, vishakapatnam, 850).
heuristic(varanasi, asansol, 444).
heuristic(varanasi, gwalior, 491).
heuristic(varanasi, surat, 1135).
heuristic(varanasi, ranchi, 323).
heuristic(varanasi, nasik, 1114).
heuristic(varanasi, ahmedabad, 1087).
heuristic(varanasi, madras, 1394).
heuristic(varanasi, calicut, 1739).
heuristic(varanasi, kolhapur, 1320).
heuristic(varanasi, amritsar, 1059).
heuristic(varanasi, vijayawada, 1010).
heuristic(varanasi, bombay, 1251).
heuristic(varanasi, hubli, 1378).
heuristic(varanasi, bhubaneshwar, 631).
heuristic(varanasi, chandigarh, 857).
heuristic(varanasi, agra, 537).
heuristic(varanasi, allahabad, 114).
heuristic(varanasi, jabalpur, 389).
heuristic(varanasi, hyderabad, 998).
heuristic(varanasi, shimla, 859).
heuristic(varanasi, pondicherry, 1528).
heuristic(varanasi, pune, 1208).
heuristic(varanasi, kanpur, 293).
heuristic(varanasi, ludhiana, 935).
heuristic(varanasi, madurai, 1789).
heuristic(varanasi, shillong, 897).
heuristic(varanasi, calcutta, 628).
heuristic(varanasi, delhi, 680).
heuristic(varanasi, cochin, 1852).
heuristic(varanasi, lucknow, 265).
heuristic(varanasi, bangalore, 1486).
heuristic(varanasi, indore, 779).
heuristic(varanasi, patna, 220).
heuristic(varanasi, baroda, 1052).
heuristic(varanasi, bhopal, 609).
heuristic(varanasi, meerut, 662).
heuristic(varanasi, coimbatore, 1714).
heuristic(varanasi, panjim, 1451).
heuristic(varanasi, jaipur, 740).
heuristic(varanasi, jullundur, 986).
heuristic(varanasi, imphal, 1108).
heuristic(jamshedpur, trivandrum, 1876).
heuristic(jamshedpur, nagpur, 757).
heuristic(jamshedpur, varanasi, 431).
heuristic(jamshedpur, jamshedpur, 0).
heuristic(jamshedpur, agartala, 532).
heuristic(jamshedpur, vishakapatnam, 650).
heuristic(jamshedpur, asansol, 126).
heuristic(jamshedpur, gwalior, 897).
heuristic(jamshedpur, surat, 1393).
heuristic(jamshedpur, ranchi, 109).
heuristic(jamshedpur, nasik, 1324).
heuristic(jamshedpur, ahmedabad, 1398).
heuristic(jamshedpur, madras, 1255).
heuristic(jamshedpur, calicut, 1697).
heuristic(jamshedpur, kolhapur, 1425).
heuristic(jamshedpur, amritsar, 1490).
heuristic(jamshedpur, vijayawada, 911).
heuristic(jamshedpur, bombay, 1446).
heuristic(jamshedpur, hubli, 1429).
heuristic(jamshedpur, bhubaneshwar, 282).
heuristic(jamshedpur, chandigarh, 1286).
heuristic(jamshedpur, agra, 959).
heuristic(jamshedpur, allahabad, 531).
heuristic(jamshedpur, jabalpur, 642).
heuristic(jamshedpur, hyderabad, 1007).
heuristic(jamshedpur, shimla, 1286).
heuristic(jamshedpur, pondicherry, 1389).
heuristic(jamshedpur, pune, 1371).
heuristic(jamshedpur, kanpur, 720).
heuristic(jamshedpur, ludhiana, 1366).
heuristic(jamshedpur, madurai, 1673).
heuristic(jamshedpur, shillong, 655).
heuristic(jamshedpur, calcutta, 224).
heuristic(jamshedpur, delhi, 1110).
heuristic(jamshedpur, cochin, 1780).
heuristic(jamshedpur, lucknow, 696).
heuristic(jamshedpur, bangalore, 1424).
heuristic(jamshedpur, indore, 1062).
heuristic(jamshedpur, patna, 331).
heuristic(jamshedpur, baroda, 1340).
heuristic(jamshedpur, bhopal, 902).
heuristic(jamshedpur, meerut, 1094).
heuristic(jamshedpur, coimbatore, 1640).
heuristic(jamshedpur, panjim, 1534).
heuristic(jamshedpur, jaipur, 1147).
heuristic(jamshedpur, jullundur, 1416).
heuristic(jamshedpur, imphal, 820).
heuristic(agartala, trivandrum, 2292).
heuristic(agartala, nagpur, 1290).
heuristic(agartala, varanasi, 858).
heuristic(agartala, jamshedpur, 532).
heuristic(agartala, agartala, 0).
heuristic(agartala, vishakapatnam, 1083).
heuristic(agartala, asansol, 440).
heuristic(agartala, gwalior, 1348).
heuristic(agartala, surat, 1921).
heuristic(agartala, ranchi, 612).
heuristic(agartala, nasik, 1856).
heuristic(agartala, ahmedabad, 1913).
heuristic(agartala, madras, 1671).
heuristic(agartala, calicut, 2157).
heuristic(agartala, kolhapur, 1947).
heuristic(agartala, amritsar, 1833).
heuristic(agartala, vijayawada, 1378).
heuristic(agartala, bombay, 1978).
heuristic(agartala, hubli, 1938).
heuristic(agartala, bhubaneshwar, 687).
heuristic(agartala, chandigarh, 1626).
heuristic(agartala, agra, 1385).
heuristic(agartala, allahabad, 972).
heuristic(agartala, jabalpur, 1160).
heuristic(agartala, hyderabad, 1514).
heuristic(agartala, shimla, 1611).
heuristic(agartala, pondicherry, 1798).
heuristic(agartala, pune, 1902).
heuristic(agartala, kanpur, 1142).
heuristic(agartala, ludhiana, 1715).
heuristic(agartala, madurai, 2086).
heuristic(agartala, shillong, 204).
heuristic(agartala, calcutta, 330).
heuristic(agartala, delhi, 1502).
heuristic(agartala, cochin, 2221).
heuristic(agartala, lucknow, 1093).
heuristic(agartala, bangalore, 1883).
heuristic(agartala, indore, 1582).
heuristic(agartala, patna, 652).
heuristic(agartala, baroda, 1861).
heuristic(agartala, bhopal, 1417).
heuristic(agartala, meerut, 1470).
heuristic(agartala, coimbatore, 2083).
heuristic(agartala, panjim, 2050).
heuristic(agartala, jaipur, 1596).
heuristic(agartala, jullundur, 1758).
heuristic(agartala, imphal, 291).
heuristic(vishakapatnam, trivandrum, 1229).
heuristic(vishakapatnam, nagpur, 580).
heuristic(vishakapatnam, varanasi, 850).
heuristic(vishakapatnam, jamshedpur, 650).
heuristic(vishakapatnam, agartala, 1083).
heuristic(vishakapatnam, vishakapatnam, 0).
heuristic(vishakapatnam, asansol, 774).
heuristic(vishakapatnam, gwalior, 1083).
heuristic(vishakapatnam, surat, 1159).
heuristic(vishakapatnam, ranchi, 667).
heuristic(vishakapatnam, nasik, 1026).
heuristic(vishakapatnam, ahmedabad, 1261).
heuristic(vishakapatnam, madras, 606).
heuristic(vishakapatnam, calicut, 1075).
heuristic(vishakapatnam, kolhapur, 961).
heuristic(vishakapatnam, amritsar, 1766).
heuristic(vishakapatnam, vijayawada, 304).
heuristic(vishakapatnam, bombay, 1103).
heuristic(vishakapatnam, hubli, 902).
heuristic(vishakapatnam, bhubaneshwar, 400).
heuristic(vishakapatnam, chandigarh, 1592).
heuristic(vishakapatnam, agra, 1185).
heuristic(vishakapatnam, allahabad, 874).
heuristic(vishakapatnam, jabalpur, 699).
heuristic(vishakapatnam, hyderabad, 504).
heuristic(vishakapatnam, shimla, 1614).
heuristic(vishakapatnam, pondicherry, 740).
heuristic(vishakapatnam, pune, 995).
heuristic(vishakapatnam, kanpur, 1020).
heuristic(vishakapatnam, ludhiana, 1649).
heuristic(vishakapatnam, madurai, 1025).
heuristic(vishakapatnam, shillong, 1256).
heuristic(vishakapatnam, calcutta, 765).
heuristic(vishakapatnam, delhi, 1364).
heuristic(vishakapatnam, cochin, 1143).
heuristic(vishakapatnam, lucknow, 1046).
heuristic(vishakapatnam, bangalore, 800).
heuristic(vishakapatnam, indore, 951).
heuristic(vishakapatnam, patna, 904).
heuristic(vishakapatnam, baroda, 1169).
heuristic(vishakapatnam, bhopal, 867).
heuristic(vishakapatnam, meerut, 1378).
heuristic(vishakapatnam, coimbatore, 1004).
heuristic(vishakapatnam, panjim, 1032).
heuristic(vishakapatnam, jaipur, 1280).
heuristic(vishakapatnam, jullundur, 1703).
heuristic(vishakapatnam, imphal, 1366).
heuristic(asansol, trivandrum, 2002).
heuristic(asansol, nagpur, 859).
heuristic(asansol, varanasi, 444).
heuristic(asansol, jamshedpur, 126).
heuristic(asansol, agartala, 440).
heuristic(asansol, vishakapatnam, 774).
heuristic(asansol, asansol, 0).
heuristic(asansol, gwalior, 931).
heuristic(asansol, surat, 1482).
heuristic(asansol, ranchi, 174).
heuristic(asansol, nasik, 1422).
heuristic(asansol, ahmedabad, 1474).
heuristic(asansol, madras, 1380).
heuristic(asansol, calicut, 1822).
heuristic(asansol, kolhapur, 1540).
heuristic(asansol, amritsar, 1484).
heuristic(asansol, vijayawada, 1037).
heuristic(asansol, bombay, 1548).
heuristic(asansol, hubli, 1549).
heuristic(asansol, bhubaneshwar, 396).
heuristic(asansol, chandigarh, 1277).
heuristic(asansol, agra, 981).
heuristic(asansol, allahabad, 554).
heuristic(asansol, jabalpur, 720).
heuristic(asansol, hyderabad, 1129).
heuristic(asansol, shimla, 1272).
heuristic(asansol, pondicherry, 1514).
heuristic(asansol, pune, 1478).
heuristic(asansol, kanpur, 737).
heuristic(asansol, ludhiana, 1361).
heuristic(asansol, madurai, 1798).
heuristic(asansol, shillong, 541).
heuristic(asansol, calcutta, 189).
heuristic(asansol, delhi, 1119).
heuristic(asansol, cochin, 1906).
heuristic(asansol, lucknow, 701).
heuristic(asansol, bangalore, 1550).
heuristic(asansol, indore, 1142).
heuristic(asansol, patna, 283).
heuristic(asansol, baroda, 1421).
heuristic(asansol, bhopal, 977).
heuristic(asansol, meerut, 1096).
heuristic(asansol, coimbatore, 1766).
heuristic(asansol, panjim, 1652).
heuristic(asansol, jaipur, 1181).
heuristic(asansol, jullundur, 1409).
heuristic(asansol, imphal, 719).
heuristic(gwalior, trivandrum, 1979).
heuristic(gwalior, nagpur, 572).
heuristic(gwalior, varanasi, 491).
heuristic(gwalior, jamshedpur, 897).
heuristic(gwalior, agartala, 1348).
heuristic(gwalior, vishakapatnam, 1083).
heuristic(gwalior, asansol, 931).
heuristic(gwalior, gwalior, 0).
heuristic(gwalior, surat, 782).
heuristic(gwalior, ranchi, 788).
heuristic(gwalior, nasik, 826).
heuristic(gwalior, ahmedabad, 670).
heuristic(gwalior, madras, 1481).
heuristic(gwalior, calicut, 1685).
heuristic(gwalior, kolhapur, 1136).
heuristic(gwalior, amritsar, 684).
heuristic(gwalior, vijayawada, 1111).
heuristic(gwalior, bombay, 964).
heuristic(gwalior, hubli, 1250).
heuristic(gwalior, bhubaneshwar, 1022).
heuristic(gwalior, chandigarh, 521).
heuristic(gwalior, agra, 108).
heuristic(gwalior, allahabad, 377).
heuristic(gwalior, jabalpur, 384).
heuristic(gwalior, hyderabad, 984).
heuristic(gwalior, shimla, 553).
heuristic(gwalior, pondicherry, 1600).
heuristic(gwalior, pune, 966).
heuristic(gwalior, kanpur, 216).
heuristic(gwalior, ludhiana, 569).
heuristic(gwalior, madurai, 1814).
heuristic(gwalior, shillong, 1375).
heuristic(gwalior, calcutta, 1109).
heuristic(gwalior, delhi, 285).
heuristic(gwalior, cochin, 1822).
heuristic(gwalior, lucknow, 284).
heuristic(gwalior, bangalore, 1476).
heuristic(gwalior, indore, 455).
heuristic(gwalior, patna, 700).
heuristic(gwalior, baroda, 669).
heuristic(gwalior, bhopal, 338).
heuristic(gwalior, meerut, 312).
heuristic(gwalior, coimbatore, 1698).
heuristic(gwalior, panjim, 1277).
heuristic(gwalior, jaipur, 251).
heuristic(gwalior, jullundur, 623).
heuristic(gwalior, imphal, 1591).
heuristic(surat, trivandrum, 1483).
heuristic(surat, nagpur, 651).
heuristic(surat, varanasi, 1135).
heuristic(surat, jamshedpur, 1393).
heuristic(surat, agartala, 1921).
heuristic(surat, vishakapatnam, 1159).
heuristic(surat, asansol, 1482).
heuristic(surat, gwalior, 782).
heuristic(surat, surat, 0).
heuristic(surat, ranchi, 1309).
heuristic(surat, nasik, 167).
heuristic(surat, ahmedabad, 207).
heuristic(surat, madras, 1202).
heuristic(surat, calicut, 1151).
heuristic(surat, kolhapur, 523).
heuristic(surat, amritsar, 1180).
heuristic(surat, vijayawada, 976).
heuristic(surat, bombay, 236).
heuristic(surat, hubli, 693).
heuristic(surat, bhubaneshwar, 1358).
heuristic(surat, chandigarh, 1133).
heuristic(surat, agra, 849).
heuristic(surat, allahabad, 1036).
heuristic(surat, jabalpur, 767).
heuristic(surat, hyderabad, 731).
heuristic(surat, shimla, 1185).
heuristic(surat, pondicherry, 1271).
heuristic(surat, pune, 317).
heuristic(surat, kanpur, 963).
heuristic(surat, ludhiana, 1123).
heuristic(surat, madurai, 1377).
heuristic(surat, shillong, 2007).
heuristic(surat, calcutta, 1613).
heuristic(surat, delhi, 940).
heuristic(surat, cochin, 1305).
heuristic(surat, lucknow, 1038).
heuristic(surat, bangalore, 1047).
heuristic(surat, indore, 357).
heuristic(surat, patna, 1351).
heuristic(surat, baroda, 129).
heuristic(surat, bhopal, 526).
heuristic(surat, meerut, 997).
heuristic(surat, coimbatore, 1216).
heuristic(surat, panjim, 643).
heuristic(surat, jaipur, 704).
heuristic(surat, jullundur, 1161).
heuristic(surat, imphal, 2200).
heuristic(ranchi, trivandrum, 1880).
heuristic(ranchi, nagpur, 686).
heuristic(ranchi, varanasi, 323).
heuristic(ranchi, jamshedpur, 109).
heuristic(ranchi, agartala, 612).
heuristic(ranchi, vishakapatnam, 667).
heuristic(ranchi, asansol, 174).
heuristic(ranchi, gwalior, 788).
heuristic(ranchi, surat, 1309).
heuristic(ranchi, ranchi, 0).
heuristic(ranchi, nasik, 1248).
heuristic(ranchi, ahmedabad, 1304).
heuristic(ranchi, madras, 1264).
heuristic(ranchi, calicut, 1683).
heuristic(ranchi, kolhapur, 1373).
heuristic(ranchi, amritsar, 1382).
heuristic(ranchi, vijayawada, 904).
heuristic(ranchi, bombay, 1375).
heuristic(ranchi, hubli, 1390).
heuristic(ranchi, bhubaneshwar, 344).
heuristic(ranchi, chandigarh, 1179).
heuristic(ranchi, agra, 850).
heuristic(ranchi, allahabad, 421).
heuristic(ranchi, jabalpur, 549).
heuristic(ranchi, hyderabad, 973).
heuristic(ranchi, shimla, 1181).
heuristic(ranchi, pondicherry, 1399).
heuristic(ranchi, pune, 1306).
heuristic(ranchi, kanpur, 610).
heuristic(ranchi, ludhiana, 1258).
heuristic(ranchi, madurai, 1679).
heuristic(ranchi, shillong, 712).
heuristic(ranchi, calcutta, 325).
heuristic(ranchi, delhi, 1000).
heuristic(ranchi, cochin, 1775).
heuristic(ranchi, lucknow, 588).
heuristic(ranchi, bangalore, 1413).
heuristic(ranchi, indore, 971).
heuristic(ranchi, patna, 253).
heuristic(ranchi, baroda, 1250).
heuristic(ranchi, bhopal, 808).
heuristic(ranchi, meerut, 985).
heuristic(ranchi, coimbatore, 1634).
heuristic(ranchi, panjim, 1488).
heuristic(ranchi, jaipur, 1039).
heuristic(ranchi, jullundur, 1309).
heuristic(ranchi, imphal, 893).
heuristic(nasik, trivandrum, 1326).
heuristic(nasik, nagpur, 567).
heuristic(nasik, varanasi, 1114).
heuristic(nasik, jamshedpur, 1324).
heuristic(nasik, agartala, 1856).
heuristic(nasik, vishakapatnam, 1026).
heuristic(nasik, asansol, 1422).
heuristic(nasik, gwalior, 826).
heuristic(nasik, surat, 167).
heuristic(nasik, ranchi, 1248).
heuristic(nasik, nasik, 0).
heuristic(nasik, ahmedabad, 362).
heuristic(nasik, madras, 1035).
heuristic(nasik, calicut, 996).
heuristic(nasik, kolhapur, 371).
heuristic(nasik, amritsar, 1300).
heuristic(nasik, vijayawada, 823).
heuristic(nasik, bombay, 140).
heuristic(nasik, hubli, 535).
heuristic(nasik, bhubaneshwar, 1258).
heuristic(nasik, chandigarh, 1233).
heuristic(nasik, agra, 908).
heuristic(nasik, allahabad, 1025).
heuristic(nasik, jabalpur, 729).
heuristic(nasik, hyderabad, 574).
heuristic(nasik, shimla, 1282).
heuristic(nasik, pondicherry, 1104).
heuristic(nasik, pune, 165).
heuristic(nasik, kanpur, 982).
heuristic(nasik, ludhiana, 1232).
heuristic(nasik, madurai, 1214).
heuristic(nasik, shillong, 1957).
heuristic(nasik, calcutta, 1538).
heuristic(nasik, delhi, 1023).
heuristic(nasik, cochin, 1149).
heuristic(nasik, lucknow, 1056).
heuristic(nasik, bangalore, 881).
heuristic(nasik, indore, 371).
heuristic(nasik, patna, 1321).
heuristic(nasik, baroda, 265).
heuristic(nasik, bhopal, 522).
heuristic(nasik, meerut, 1076).
heuristic(nasik, coimbatore, 1056).
heuristic(nasik, panjim, 501).
heuristic(nasik, jaipur, 797).
heuristic(nasik, jullundur, 1274).
heuristic(nasik, imphal, 2141).
heuristic(ahmedabad, trivandrum, 1687).
heuristic(ahmedabad, nagpur, 705).
heuristic(ahmedabad, varanasi, 1087).
heuristic(ahmedabad, jamshedpur, 1398).
heuristic(ahmedabad, agartala, 1913).
heuristic(ahmedabad, vishakapatnam, 1261).
heuristic(ahmedabad, asansol, 1474).
heuristic(ahmedabad, gwalior, 670).
heuristic(ahmedabad, surat, 207).
heuristic(ahmedabad, ranchi, 1304).
heuristic(ahmedabad, nasik, 362).
heuristic(ahmedabad, ahmedabad, 0).
heuristic(ahmedabad, madras, 1376).
heuristic(ahmedabad, calicut, 1355).
heuristic(ahmedabad, kolhapur, 728).
heuristic(ahmedabad, amritsar, 984).
heuristic(ahmedabad, vijayawada, 1116).
heuristic(ahmedabad, bombay, 443).
heuristic(ahmedabad, hubli, 896).
heuristic(ahmedabad, bhubaneshwar, 1405).
heuristic(ahmedabad, chandigarh, 953).
heuristic(ahmedabad, agra, 716).
heuristic(ahmedabad, allahabad, 979).
heuristic(ahmedabad, jabalpur, 756).
heuristic(ahmedabad, hyderabad, 882).
heuristic(ahmedabad, shimla, 1007).
heuristic(ahmedabad, pondicherry, 1454).
heuristic(ahmedabad, pune, 521).
heuristic(ahmedabad, kanpur, 872).
heuristic(ahmedabad, ludhiana, 934).
heuristic(ahmedabad, madurai, 1576).
heuristic(ahmedabad, shillong, 1980).
heuristic(ahmedabad, calcutta, 1622).
heuristic(ahmedabad, delhi, 778).
heuristic(ahmedabad, cochin, 1509).
heuristic(ahmedabad, lucknow, 946).
heuristic(ahmedabad, bangalore, 1241).
heuristic(ahmedabad, indore, 340).
heuristic(ahmedabad, patna, 1307).
heuristic(ahmedabad, baroda, 103).
heuristic(ahmedabad, bhopal, 497).
heuristic(ahmedabad, meerut, 838).
heuristic(ahmedabad, coimbatore, 1418).
heuristic(ahmedabad, panjim, 850).
heuristic(ahmedabad, jaipur, 540).
heuristic(ahmedabad, jullundur, 970).
heuristic(ahmedabad, imphal, 2183).
heuristic(madras, trivandrum, 624).
heuristic(madras, nagpur, 909).
heuristic(madras, varanasi, 1394).
heuristic(madras, jamshedpur, 1255).
heuristic(madras, agartala, 1671).
heuristic(madras, vishakapatnam, 606).
heuristic(madras, asansol, 1380).
heuristic(madras, gwalior, 1481).
heuristic(madras, surat, 1202).
heuristic(madras, ranchi, 1264).
heuristic(madras, nasik, 1035).
heuristic(madras, ahmedabad, 1376).
heuristic(madras, madras, 0).
heuristic(madras, calicut, 526).
heuristic(madras, kolhapur, 762).
heuristic(madras, amritsar, 2140).
heuristic(madras, vijayawada, 386).
heuristic(madras, bombay, 1034).
heuristic(madras, hubli, 610).
heuristic(madras, bhubaneshwar, 1001).
heuristic(madras, chandigarh, 2000).
heuristic(madras, agra, 1589).
heuristic(madras, allahabad, 1388).
heuristic(madras, jabalpur, 1126).
heuristic(madras, hyderabad, 517).
heuristic(madras, shimla, 2034).
heuristic(madras, pondicherry, 136).
heuristic(madras, pune, 916).
heuristic(madras, kanpur, 1491).
heuristic(madras, ludhiana, 2037).
heuristic(madras, madurai, 419).
heuristic(madras, shillong, 1852).
heuristic(madras, calcutta, 1364).
heuristic(madras, delhi, 1762).
heuristic(madras, cochin, 556).
heuristic(madras, lucknow, 1537).
heuristic(madras, bangalore, 288).
heuristic(madras, indore, 1172).
heuristic(madras, patna, 1489).
heuristic(madras, baroda, 1273).
heuristic(madras, bhopal, 1175).
heuristic(madras, meerut, 1793).
heuristic(madras, coimbatore, 425).
heuristic(madras, panjim, 744).
heuristic(madras, jaipur, 1611).
heuristic(madras, jullundur, 2089).
heuristic(madras, imphal, 1945).
heuristic(calicut, trivandrum, 334).
heuristic(calicut, nagpur, 1156).
heuristic(calicut, varanasi, 1739).
heuristic(calicut, jamshedpur, 1697).
heuristic(calicut, agartala, 2157).
heuristic(calicut, vishakapatnam, 1075).
heuristic(calicut, asansol, 1822).
heuristic(calicut, gwalior, 1685).
heuristic(calicut, surat, 1151).
heuristic(calicut, ranchi, 1683).
heuristic(calicut, nasik, 996).
heuristic(calicut, ahmedabad, 1355).
heuristic(calicut, madras, 526).
heuristic(calicut, calicut, 0).
heuristic(calicut, kolhapur, 627).
heuristic(calicut, amritsar, 2271).
heuristic(calicut, vijayawada, 786).
heuristic(calicut, bombay, 925).
heuristic(calicut, hubli, 463).
heuristic(calicut, bhubaneshwar, 1472).
heuristic(calicut, chandigarh, 2171).
heuristic(calicut, agra, 1788).
heuristic(calicut, allahabad, 1703).
heuristic(calicut, jabalpur, 1398).
heuristic(calicut, hyderabad, 742).
heuristic(calicut, shimla, 2214).
heuristic(calicut, pondicherry, 443).
heuristic(calicut, pune, 835).
heuristic(calicut, kanpur, 1758).
heuristic(calicut, ludhiana, 2187).
heuristic(calicut, madurai, 296).
heuristic(calicut, shillong, 2328).
heuristic(calicut, calcutta, 1837).
heuristic(calicut, delhi, 1941).
heuristic(calicut, cochin, 154).
heuristic(calicut, lucknow, 1818).
heuristic(calicut, bangalore, 275).
heuristic(calicut, indore, 1276).
heuristic(calicut, patna, 1877).
heuristic(calicut, baroda, 1261).
heuristic(calicut, bhopal, 1348).
heuristic(calicut, meerut, 1984).
heuristic(calicut, coimbatore, 131).
heuristic(calicut, panjim, 517).
heuristic(calicut, jaipur, 1743).
heuristic(calicut, jullundur, 2235).
heuristic(calicut, imphal, 2439).
heuristic(kolhapur, trivandrum, 960).
heuristic(kolhapur, nagpur, 711).
heuristic(kolhapur, varanasi, 1320).
heuristic(kolhapur, jamshedpur, 1425).
heuristic(kolhapur, agartala, 1947).
heuristic(kolhapur, vishakapatnam, 961).
heuristic(kolhapur, asansol, 1540).
heuristic(kolhapur, gwalior, 1136).
heuristic(kolhapur, surat, 523).
heuristic(kolhapur, ranchi, 1373).
heuristic(kolhapur, nasik, 371).
heuristic(kolhapur, ahmedabad, 728).
heuristic(kolhapur, madras, 762).
heuristic(kolhapur, calicut, 627).
heuristic(kolhapur, kolhapur, 0).
heuristic(kolhapur, amritsar, 1665).
heuristic(kolhapur, vijayawada, 684).
heuristic(kolhapur, bombay, 302).
heuristic(kolhapur, hubli, 175).
heuristic(kolhapur, bhubaneshwar, 1287).
heuristic(kolhapur, chandigarh, 1585).
heuristic(kolhapur, agra, 1230).
heuristic(kolhapur, allahabad, 1253).
heuristic(kolhapur, jabalpur, 936).
heuristic(kolhapur, hyderabad, 458).
heuristic(kolhapur, shimla, 1632).
heuristic(kolhapur, pondicherry, 799).
heuristic(kolhapur, pune, 208).
heuristic(kolhapur, kanpur, 1256).
heuristic(kolhapur, ludhiana, 1591).
heuristic(kolhapur, madurai, 862).
heuristic(kolhapur, shillong, 2080).
heuristic(kolhapur, calcutta, 1618).
heuristic(kolhapur, delhi, 1365).
heuristic(kolhapur, cochin, 781).
heuristic(kolhapur, lucknow, 1326).
heuristic(kolhapur, bangalore, 549).
heuristic(kolhapur, indore, 692).
heuristic(kolhapur, patna, 1504).
heuristic(kolhapur, baroda, 635).
heuristic(kolhapur, bhopal, 803).
heuristic(kolhapur, meerut, 1414).
heuristic(kolhapur, coimbatore, 696).
heuristic(kolhapur, panjim, 141).
heuristic(kolhapur, jaipur, 1149).
heuristic(kolhapur, jullundur, 1635).
heuristic(kolhapur, imphal, 2238).
heuristic(amritsar, trivandrum, 2586).
heuristic(amritsar, nagpur, 1241).
heuristic(amritsar, varanasi, 1059).
heuristic(amritsar, jamshedpur, 1490).
heuristic(amritsar, agartala, 1833).
heuristic(amritsar, vishakapatnam, 1766).
heuristic(amritsar, asansol, 1484).
heuristic(amritsar, gwalior, 684).
heuristic(amritsar, surat, 1180).
heuristic(amritsar, ranchi, 1382).
heuristic(amritsar, nasik, 1300).
heuristic(amritsar, ahmedabad, 984).
heuristic(amritsar, madras, 2140).
heuristic(amritsar, calicut, 2271).
heuristic(amritsar, kolhapur, 1665).
heuristic(amritsar, amritsar, 0).
heuristic(amritsar, vijayawada, 1783).
heuristic(amritsar, bombay, 1413).
heuristic(amritsar, hubli, 1812).
heuristic(amritsar, bhubaneshwar, 1670).
heuristic(amritsar, chandigarh, 208).
heuristic(amritsar, agra, 582).
heuristic(amritsar, allahabad, 970).
heuristic(amritsar, jabalpur, 1068).
heuristic(amritsar, hyderabad, 1628).
heuristic(amritsar, shimla, 226).
heuristic(amritsar, pondicherry, 2251).
heuristic(amritsar, pune, 1464).
heuristic(amritsar, kanpur, 784).
heuristic(amritsar, ludhiana, 124).
heuristic(amritsar, madurai, 2440).
heuristic(amritsar, shillong, 1793).
heuristic(amritsar, calcutta, 1673).
heuristic(amritsar, delhi, 403).
heuristic(amritsar, cochin, 2418).
heuristic(amritsar, lucknow, 795).
heuristic(amritsar, bangalore, 2097).
heuristic(amritsar, indore, 997).
heuristic(amritsar, patna, 1206).
heuristic(amritsar, baroda, 1052).
heuristic(amritsar, bhopal, 966).
heuristic(amritsar, meerut, 402).
heuristic(amritsar, coimbatore, 2306).
heuristic(amritsar, panjim, 1800).
heuristic(amritsar, jaipur, 533).
heuristic(amritsar, jullundur, 75).
heuristic(amritsar, imphal, 2016).
heuristic(vijayawada, trivandrum, 979).
heuristic(vijayawada, nagpur, 542).
heuristic(vijayawada, varanasi, 1010).
heuristic(vijayawada, jamshedpur, 911).
heuristic(vijayawada, agartala, 1378).
heuristic(vijayawada, vishakapatnam, 304).
heuristic(vijayawada, asansol, 1037).
heuristic(vijayawada, gwalior, 1111).
heuristic(vijayawada, surat, 976).
heuristic(vijayawada, ranchi, 904).
heuristic(vijayawada, nasik, 823).
heuristic(vijayawada, ahmedabad, 1116).
heuristic(vijayawada, madras, 386).
heuristic(vijayawada, calicut, 786).
heuristic(vijayawada, kolhapur, 684).
heuristic(vijayawada, amritsar, 1783).
heuristic(vijayawada, vijayawada, 0).
heuristic(vijayawada, bombay, 872).
heuristic(vijayawada, hubli, 605).
heuristic(vijayawada, bhubaneshwar, 691).
heuristic(vijayawada, chandigarh, 1632).
heuristic(vijayawada, agra, 1219).
heuristic(vijayawada, allahabad, 1002).
heuristic(vijayawada, jabalpur, 745).
heuristic(vijayawada, hyderabad, 250).
heuristic(vijayawada, shimla, 1663).
heuristic(vijayawada, pondicherry, 518).
heuristic(vijayawada, pune, 755).
heuristic(vijayawada, kanpur, 1108).
heuristic(vijayawada, ludhiana, 1675).
heuristic(vijayawada, madurai, 782).
heuristic(vijayawada, shillong, 1543).
heuristic(vijayawada, calcutta, 1054).
heuristic(vijayawada, delhi, 1395).
heuristic(vijayawada, cochin, 871).
heuristic(vijayawada, lucknow, 1152).
heuristic(vijayawada, bangalore, 513).
heuristic(vijayawada, indore, 855).
heuristic(vijayawada, patna, 1116).
heuristic(vijayawada, baroda, 1016).
heuristic(vijayawada, bhopal, 825).
heuristic(vijayawada, meerut, 1422).
heuristic(vijayawada, coimbatore, 730).
heuristic(vijayawada, panjim, 739).
heuristic(vijayawada, jaipur, 1263).
heuristic(vijayawada, jullundur, 1728).
heuristic(vijayawada, imphal, 1664).
heuristic(bombay, trivandrum, 1258).
heuristic(bombay, nagpur, 689).
heuristic(bombay, varanasi, 1251).
heuristic(bombay, jamshedpur, 1446).
heuristic(bombay, agartala, 1978).
heuristic(bombay, vishakapatnam, 1103).
heuristic(bombay, asansol, 1548).
heuristic(bombay, gwalior, 964).
heuristic(bombay, surat, 236).
heuristic(bombay, ranchi, 1375).
heuristic(bombay, nasik, 140).
heuristic(bombay, ahmedabad, 443).
heuristic(bombay, madras, 1034).
heuristic(bombay, calicut, 925).
heuristic(bombay, kolhapur, 302).
heuristic(bombay, amritsar, 1413).
heuristic(bombay, vijayawada, 872).
heuristic(bombay, bombay, 0).
heuristic(bombay, hubli, 477).
heuristic(bombay, bhubaneshwar, 1364).
heuristic(bombay, chandigarh, 1356).
heuristic(bombay, agra, 1044).
heuristic(bombay, allahabad, 1164).
heuristic(bombay, jabalpur, 864).
heuristic(bombay, hyderabad, 622).
heuristic(bombay, shimla, 1407).
heuristic(bombay, pondicherry, 1087).
heuristic(bombay, pune, 120).
heuristic(bombay, kanpur, 1122).
heuristic(bombay, ludhiana, 1350).
heuristic(bombay, madurai, 1165).
heuristic(bombay, shillong, 2086).
heuristic(bombay, calcutta, 1657).
heuristic(bombay, delhi, 1153).
heuristic(bombay, cochin, 1079).
heuristic(bombay, lucknow, 1196).
heuristic(bombay, bangalore, 847).
heuristic(bombay, indore, 511).
heuristic(bombay, patna, 1456).
heuristic(bombay, baroda, 361).
heuristic(bombay, bhopal, 662).
heuristic(bombay, meerut, 1207).
heuristic(bombay, coimbatore, 999).
heuristic(bombay, panjim, 411).
heuristic(bombay, jaipur, 922).
heuristic(bombay, jullundur, 1391).
heuristic(bombay, imphal, 2265).
heuristic(hubli, trivandrum, 791).
heuristic(hubli, nagpur, 768).
heuristic(hubli, varanasi, 1378).
heuristic(hubli, jamshedpur, 1429).
heuristic(hubli, agartala, 1938).
heuristic(hubli, vishakapatnam, 902).
heuristic(hubli, asansol, 1549).
heuristic(hubli, gwalior, 1250).
heuristic(hubli, surat, 693).
heuristic(hubli, ranchi, 1390).
heuristic(hubli, nasik, 535).
heuristic(hubli, ahmedabad, 896).
heuristic(hubli, madras, 610).
heuristic(hubli, calicut, 463).
heuristic(hubli, kolhapur, 175).
heuristic(hubli, amritsar, 1812).
heuristic(hubli, vijayawada, 605).
heuristic(hubli, bombay, 477).
heuristic(hubli, hubli, 0).
heuristic(hubli, bhubaneshwar, 1260).
heuristic(hubli, chandigarh, 1720).
heuristic(hubli, agra, 1349).
heuristic(hubli, allahabad, 1322).
heuristic(hubli, jabalpur, 1006).
heuristic(hubli, hyderabad, 424).
heuristic(hubli, shimla, 1765).
heuristic(hubli, pondicherry, 633).
heuristic(hubli, pune, 376).
heuristic(hubli, kanpur, 1348).
heuristic(hubli, ludhiana, 1732).
heuristic(hubli, madurai, 688).
heuristic(hubli, shillong, 2083).
heuristic(hubli, calcutta, 1607).
heuristic(hubli, delhi, 1493).
heuristic(hubli, cochin, 615).
heuristic(hubli, lucknow, 1414).
heuristic(hubli, bangalore, 377).
heuristic(hubli, indore, 823).
heuristic(hubli, patna, 1546).
heuristic(hubli, baroda, 800).
heuristic(hubli, bhopal, 911).
heuristic(hubli, meerut, 1540).
heuristic(hubli, coimbatore, 523).
heuristic(hubli, panjim, 140).
heuristic(hubli, jaipur, 1288).
heuristic(hubli, jullundur, 1778).
heuristic(hubli, imphal, 2228).
heuristic(bhubaneshwar, trivandrum, 1625).
heuristic(bhubaneshwar, nagpur, 708).
heuristic(bhubaneshwar, varanasi, 631).
heuristic(bhubaneshwar, jamshedpur, 282).
heuristic(bhubaneshwar, agartala, 687).
heuristic(bhubaneshwar, vishakapatnam, 400).
heuristic(bhubaneshwar, asansol, 396).
heuristic(bhubaneshwar, gwalior, 1022).
heuristic(bhubaneshwar, surat, 1358).
heuristic(bhubaneshwar, ranchi, 344).
heuristic(bhubaneshwar, nasik, 1258).
heuristic(bhubaneshwar, ahmedabad, 1405).
heuristic(bhubaneshwar, madras, 1001).
heuristic(bhubaneshwar, calicut, 1472).
heuristic(bhubaneshwar, kolhapur, 1287).
heuristic(bhubaneshwar, amritsar, 1670).
heuristic(bhubaneshwar, vijayawada, 691).
heuristic(bhubaneshwar, bombay, 1364).
heuristic(bhubaneshwar, hubli, 1260).
heuristic(bhubaneshwar, bhubaneshwar, 0).
heuristic(bhubaneshwar, chandigarh, 1474).
heuristic(bhubaneshwar, agra, 1105).
heuristic(bhubaneshwar, allahabad, 703).
heuristic(bhubaneshwar, jabalpur, 686).
heuristic(bhubaneshwar, hyderabad, 838).
heuristic(bhubaneshwar, shimla, 1483).
heuristic(bhubaneshwar, pondicherry, 1133).
heuristic(bhubaneshwar, pune, 1272).
heuristic(bhubaneshwar, kanpur, 886).
heuristic(bhubaneshwar, ludhiana, 1546).
heuristic(bhubaneshwar, madurai, 1420).
heuristic(bhubaneshwar, shillong, 856).
heuristic(bhubaneshwar, calcutta, 365).
heuristic(bhubaneshwar, delhi, 1273).
heuristic(bhubaneshwar, cochin, 1543).
heuristic(bhubaneshwar, lucknow, 883).
heuristic(bhubaneshwar, bangalore, 1198).
heuristic(bhubaneshwar, indore, 1067).
heuristic(bhubaneshwar, patna, 596).
heuristic(bhubaneshwar, baroda, 1330).
heuristic(bhubaneshwar, bhopal, 930).
heuristic(bhubaneshwar, meerut, 1268).
heuristic(bhubaneshwar, coimbatore, 1403).
heuristic(bhubaneshwar, panjim, 1379).
heuristic(bhubaneshwar, jaipur, 1261).
heuristic(bhubaneshwar, jullundur, 1599).
heuristic(bhubaneshwar, imphal, 974).
heuristic(chandigarh, trivandrum, 2477).
heuristic(chandigarh, nagpur, 1092).
heuristic(chandigarh, varanasi, 857).
heuristic(chandigarh, jamshedpur, 1286).
heuristic(chandigarh, agartala, 1626).
heuristic(chandigarh, vishakapatnam, 1592).
heuristic(chandigarh, asansol, 1277).
heuristic(chandigarh, gwalior, 521).
heuristic(chandigarh, surat, 1133).
heuristic(chandigarh, ranchi, 1179).
heuristic(chandigarh, nasik, 1233).
heuristic(chandigarh, ahmedabad, 953).
heuristic(chandigarh, madras, 2000).
heuristic(chandigarh, calicut, 2171).
heuristic(chandigarh, kolhapur, 1585).
heuristic(chandigarh, amritsar, 208).
heuristic(chandigarh, vijayawada, 1632).
heuristic(chandigarh, bombay, 1356).
heuristic(chandigarh, hubli, 1720).
heuristic(chandigarh, bhubaneshwar, 1474).
heuristic(chandigarh, chandigarh, 0).
heuristic(chandigarh, agra, 414).
heuristic(chandigarh, allahabad, 772).
heuristic(chandigarh, jabalpur, 899).
heuristic(chandigarh, hyderabad, 1496).
heuristic(chandigarh, shimla, 55).
heuristic(chandigarh, pondicherry, 2116).
heuristic(chandigarh, pune, 1392).
heuristic(chandigarh, kanpur, 590).
heuristic(chandigarh, ludhiana, 90).
heuristic(chandigarh, madurai, 2321).
heuristic(chandigarh, shillong, 1589).
heuristic(chandigarh, calcutta, 1466).
heuristic(chandigarh, delhi, 238).
heuristic(chandigarh, cochin, 2314).
heuristic(chandigarh, lucknow, 594).
heuristic(chandigarh, bangalore, 1980).
heuristic(chandigarh, indore, 897).
heuristic(chandigarh, patna, 999).
heuristic(chandigarh, baroda, 1004).
heuristic(chandigarh, bhopal, 835).
heuristic(chandigarh, meerut, 214).
heuristic(chandigarh, coimbatore, 2196).
heuristic(chandigarh, panjim, 1723).
heuristic(chandigarh, jaipur, 436).
heuristic(chandigarh, jullundur, 132).
heuristic(chandigarh, imphal, 1813).
heuristic(agra, trivandrum, 2084).
heuristic(agra, nagpur, 680).
heuristic(agra, varanasi, 537).
heuristic(agra, jamshedpur, 959).
heuristic(agra, agartala, 1385).
heuristic(agra, vishakapatnam, 1185).
heuristic(agra, asansol, 981).
heuristic(agra, gwalior, 108).
heuristic(agra, surat, 849).
heuristic(agra, ranchi, 850).
heuristic(agra, nasik, 908).
heuristic(agra, ahmedabad, 716).
heuristic(agra, madras, 1589).
heuristic(agra, calicut, 1788).
heuristic(agra, kolhapur, 1230).
heuristic(agra, amritsar, 582).
heuristic(agra, vijayawada, 1219).
heuristic(agra, bombay, 1044).
heuristic(agra, hubli, 1349).
heuristic(agra, bhubaneshwar, 1105).
heuristic(agra, chandigarh, 414).
heuristic(agra, agra, 0).
heuristic(agra, allahabad, 429).
heuristic(agra, jabalpur, 487).
heuristic(agra, hyderabad, 1091).
heuristic(agra, shimla, 445).
heuristic(agra, pondicherry, 1708).
heuristic(agra, pune, 1054).
heuristic(agra, kanpur, 245).
heuristic(agra, ludhiana, 465).
heuristic(agra, madurai, 1921).
heuristic(agra, shillong, 1396).
heuristic(agra, calcutta, 1164).
heuristic(agra, delhi, 180).
heuristic(agra, cochin, 1927).
heuristic(agra, lucknow, 294).
heuristic(agra, bangalore, 1582).
heuristic(agra, indore, 542).
heuristic(agra, patna, 732).
heuristic(agra, baroda, 729).
heuristic(agra, bhopal, 440).
heuristic(agra, meerut, 203).
heuristic(agra, coimbatore, 1803).
heuristic(agra, panjim, 1371).
heuristic(agra, jaipur, 222).
heuristic(agra, jullundur, 519).
heuristic(agra, imphal, 1616).
heuristic(allahabad, trivandrum, 1957).
heuristic(allahabad, nagpur, 555).
heuristic(allahabad, varanasi, 114).
heuristic(allahabad, jamshedpur, 531).
heuristic(allahabad, agartala, 972).
heuristic(allahabad, vishakapatnam, 874).
heuristic(allahabad, asansol, 554).
heuristic(allahabad, gwalior, 377).
heuristic(allahabad, surat, 1036).
heuristic(allahabad, ranchi, 421).
heuristic(allahabad, nasik, 1025).
heuristic(allahabad, ahmedabad, 979).
heuristic(allahabad, madras, 1388).
heuristic(allahabad, calicut, 1703).
heuristic(allahabad, kolhapur, 1253).
heuristic(allahabad, amritsar, 970).
heuristic(allahabad, vijayawada, 1002).
heuristic(allahabad, bombay, 1164).
heuristic(allahabad, hubli, 1322).
heuristic(allahabad, bhubaneshwar, 703).
heuristic(allahabad, chandigarh, 772).
heuristic(allahabad, agra, 429).
heuristic(allahabad, allahabad, 0).
heuristic(allahabad, jabalpur, 318).
heuristic(allahabad, hyderabad, 962).
heuristic(allahabad, shimla, 780).
heuristic(allahabad, pondicherry, 1519).
heuristic(allahabad, pune, 1128).
heuristic(allahabad, kanpur, 189).
heuristic(allahabad, ludhiana, 846).
heuristic(allahabad, madurai, 1771).
heuristic(allahabad, shillong, 1010).
heuristic(allahabad, calcutta, 736).
heuristic(allahabad, delhi, 580).
heuristic(allahabad, cochin, 1822).
heuristic(allahabad, lucknow, 181).
heuristic(allahabad, bangalore, 1458).
heuristic(allahabad, indore, 680).
heuristic(allahabad, patna, 332).
heuristic(allahabad, baroda, 948).
heuristic(allahabad, bhopal, 511).
heuristic(allahabad, meerut, 569).
heuristic(allahabad, coimbatore, 1686).
heuristic(allahabad, panjim, 1387).
heuristic(allahabad, jaipur, 627).
heuristic(allahabad, jullundur, 898).
heuristic(allahabad, imphal, 1222).
heuristic(jabalpur, trivandrum, 1666).
heuristic(jabalpur, nagpur, 242).
heuristic(jabalpur, varanasi, 389).
heuristic(jabalpur, jamshedpur, 642).
heuristic(jabalpur, agartala, 1160).
heuristic(jabalpur, vishakapatnam, 699).
heuristic(jabalpur, asansol, 720).
heuristic(jabalpur, gwalior, 384).
heuristic(jabalpur, surat, 767).
heuristic(jabalpur, ranchi, 549).
heuristic(jabalpur, nasik, 729).
heuristic(jabalpur, ahmedabad, 756).
heuristic(jabalpur, madras, 1126).
heuristic(jabalpur, calicut, 1398).
heuristic(jabalpur, kolhapur, 936).
heuristic(jabalpur, amritsar, 1068).
heuristic(jabalpur, vijayawada, 745).
heuristic(jabalpur, bombay, 864).
heuristic(jabalpur, hubli, 1006).
heuristic(jabalpur, bhubaneshwar, 686).
heuristic(jabalpur, chandigarh, 899).
heuristic(jabalpur, agra, 487).
heuristic(jabalpur, allahabad, 318).
heuristic(jabalpur, jabalpur, 0).
heuristic(jabalpur, hyderabad, 662).
heuristic(jabalpur, shimla, 925).
heuristic(jabalpur, pondicherry, 1251).
heuristic(jabalpur, pune, 818).
heuristic(jabalpur, kanpur, 368).
heuristic(jabalpur, ludhiana, 952).
heuristic(jabalpur, madurai, 1487).
heuristic(jabalpur, shillong, 1240).
heuristic(jabalpur, calcutta, 866).
heuristic(jabalpur, delhi, 667).
heuristic(jabalpur, cochin, 1523).
heuristic(jabalpur, lucknow, 422).
heuristic(jabalpur, bangalore, 1162).
heuristic(jabalpur, indore, 423).
heuristic(jabalpur, patna, 593).
heuristic(jabalpur, baroda, 702).
heuristic(jabalpur, bhopal, 260).
heuristic(jabalpur, meerut, 686).
heuristic(jabalpur, coimbatore, 1390).
heuristic(jabalpur, panjim, 1069).
heuristic(jabalpur, jaipur, 592).
heuristic(jabalpur, jullundur, 1006).
heuristic(jabalpur, imphal, 1435).
heuristic(hyderabad, trivandrum, 1005).
heuristic(hyderabad, nagpur, 424).
heuristic(hyderabad, varanasi, 998).
heuristic(hyderabad, jamshedpur, 1007).
heuristic(hyderabad, agartala, 1514).
heuristic(hyderabad, vishakapatnam, 504).
heuristic(hyderabad, asansol, 1129).
heuristic(hyderabad, gwalior, 984).
heuristic(hyderabad, surat, 731).
heuristic(hyderabad, ranchi, 973).
heuristic(hyderabad, nasik, 574).
heuristic(hyderabad, ahmedabad, 882).
heuristic(hyderabad, madras, 517).
heuristic(hyderabad, calicut, 742).
heuristic(hyderabad, kolhapur, 458).
heuristic(hyderabad, amritsar, 1628).
heuristic(hyderabad, vijayawada, 250).
heuristic(hyderabad, bombay, 622).
heuristic(hyderabad, hubli, 424).
heuristic(hyderabad, bhubaneshwar, 838).
heuristic(hyderabad, chandigarh, 1496).
heuristic(hyderabad, agra, 1091).
heuristic(hyderabad, allahabad, 962).
heuristic(hyderabad, jabalpur, 662).
heuristic(hyderabad, hyderabad, 0).
heuristic(hyderabad, shimla, 1533).
heuristic(hyderabad, pondicherry, 623).
heuristic(hyderabad, pune, 506).
heuristic(hyderabad, kanpur, 1027).
heuristic(hyderabad, ludhiana, 1528).
heuristic(hyderabad, madurai, 832).
heuristic(hyderabad, shillong, 1660).
heuristic(hyderabad, calcutta, 1184).
heuristic(hyderabad, delhi, 1259).
heuristic(hyderabad, cochin, 862).
heuristic(hyderabad, lucknow, 1084).
heuristic(hyderabad, bangalore, 501).
heuristic(hyderabad, indore, 655).
heuristic(hyderabad, patna, 1146).
heuristic(hyderabad, baroda, 780).
heuristic(hyderabad, bhopal, 664).
heuristic(hyderabad, meerut, 1294).
heuristic(hyderabad, coimbatore, 728).
heuristic(hyderabad, panjim, 540).
heuristic(hyderabad, jaipur, 1097).
heuristic(hyderabad, jullundur, 1580).
heuristic(hyderabad, imphal, 1804).
heuristic(shimla, trivandrum, 2518).
heuristic(shimla, nagpur, 1125).
heuristic(shimla, varanasi, 859).
heuristic(shimla, jamshedpur, 1286).
heuristic(shimla, agartala, 1611).
heuristic(shimla, vishakapatnam, 1614).
heuristic(shimla, asansol, 1272).
heuristic(shimla, gwalior, 553).
heuristic(shimla, surat, 1185).
heuristic(shimla, ranchi, 1181).
heuristic(shimla, nasik, 1282).
heuristic(shimla, ahmedabad, 1007).
heuristic(shimla, madras, 2034).
heuristic(shimla, calicut, 2214).
heuristic(shimla, kolhapur, 1632).
heuristic(shimla, amritsar, 226).
heuristic(shimla, vijayawada, 1663).
heuristic(shimla, bombay, 1407).
heuristic(shimla, hubli, 1765).
heuristic(shimla, bhubaneshwar, 1483).
heuristic(shimla, chandigarh, 55).
heuristic(shimla, agra, 445).
heuristic(shimla, allahabad, 780).
heuristic(shimla, jabalpur, 925).
heuristic(shimla, hyderabad, 1533).
heuristic(shimla, shimla, 0).
heuristic(shimla, pondicherry, 2152).
heuristic(shimla, pune, 1440).
heuristic(shimla, kanpur, 603).
heuristic(shimla, ludhiana, 127).
heuristic(shimla, madurai, 2360).
heuristic(shimla, shillong, 1567).
heuristic(shimla, calcutta, 1461).
heuristic(shimla, delhi, 275).
heuristic(shimla, cochin, 2357).
heuristic(shimla, lucknow, 600).
heuristic(shimla, bangalore, 2019).
heuristic(shimla, indore, 942).
heuristic(shimla, patna, 992).
heuristic(shimla, baroda, 1056).
heuristic(shimla, bhopal, 874).
heuristic(shimla, meerut, 241).
heuristic(shimla, coimbatore, 2237).
heuristic(shimla, panjim, 1771).
heuristic(shimla, jaipur, 486).
heuristic(shimla, jullundur, 154).
heuristic(shimla, imphal, 1790).
heuristic(pondicherry, trivandrum, 494).
heuristic(pondicherry, nagpur, 1029).
heuristic(pondicherry, varanasi, 1528).
heuristic(pondicherry, jamshedpur, 1389).
heuristic(pondicherry, agartala, 1798).
heuristic(pondicherry, vishakapatnam, 740).
heuristic(pondicherry, asansol, 1514).
heuristic(pondicherry, gwalior, 1600).
heuristic(pondicherry, surat, 1271).
heuristic(pondicherry, ranchi, 1399).
heuristic(pondicherry, nasik, 1104).
heuristic(pondicherry, ahmedabad, 1454).
heuristic(pondicherry, madras, 136).
heuristic(pondicherry, calicut, 443).
heuristic(pondicherry, kolhapur, 799).
heuristic(pondicherry, amritsar, 2251).
heuristic(pondicherry, vijayawada, 518).
heuristic(pondicherry, bombay, 1087).
heuristic(pondicherry, hubli, 633).
heuristic(pondicherry, bhubaneshwar, 1133).
heuristic(pondicherry, chandigarh, 2116).
heuristic(pondicherry, agra, 1708).
heuristic(pondicherry, allahabad, 1519).
heuristic(pondicherry, jabalpur, 1251).
heuristic(pondicherry, hyderabad, 623).
heuristic(pondicherry, shimla, 2152).
heuristic(pondicherry, pondicherry, 0).
heuristic(pondicherry, pune, 971).
heuristic(pondicherry, kanpur, 1618).
heuristic(pondicherry, ludhiana, 2151).
heuristic(pondicherry, madurai, 288).
heuristic(pondicherry, shillong, 1982).
heuristic(pondicherry, calcutta, 1494).
heuristic(pondicherry, delhi, 1879).
heuristic(pondicherry, cochin, 444).
heuristic(pondicherry, lucknow, 1665).
heuristic(pondicherry, bangalore, 265).
heuristic(pondicherry, indore, 1272).
heuristic(pondicherry, patna, 1624).
heuristic(pondicherry, baroda, 1352).
heuristic(pondicherry, bhopal, 1286).
heuristic(pondicherry, meerut, 1911).
heuristic(pondicherry, coimbatore, 325).
heuristic(pondicherry, panjim, 757).
heuristic(pondicherry, jaipur, 1720).
heuristic(pondicherry, jullundur, 2203).
heuristic(pondicherry, imphal, 2069).
heuristic(pune, trivandrum, 1166).
heuristic(pune, nagpur, 621).
heuristic(pune, varanasi, 1208).
heuristic(pune, jamshedpur, 1371).
heuristic(pune, agartala, 1902).
heuristic(pune, vishakapatnam, 995).
heuristic(pune, asansol, 1478).
heuristic(pune, gwalior, 966).
heuristic(pune, surat, 317).
heuristic(pune, ranchi, 1306).
heuristic(pune, nasik, 165).
heuristic(pune, ahmedabad, 521).
heuristic(pune, madras, 916).
heuristic(pune, calicut, 835).
heuristic(pune, kolhapur, 208).
heuristic(pune, amritsar, 1464).
heuristic(pune, vijayawada, 755).
heuristic(pune, bombay, 120).
heuristic(pune, hubli, 376).
heuristic(pune, bhubaneshwar, 1272).
heuristic(pune, chandigarh, 1392).
heuristic(pune, agra, 1054).
heuristic(pune, allahabad, 1128).
heuristic(pune, jabalpur, 818).
heuristic(pune, hyderabad, 506).
heuristic(pune, shimla, 1440).
heuristic(pune, pondicherry, 971).
heuristic(pune, pune, 0).
heuristic(pune, kanpur, 1106).
heuristic(pune, ludhiana, 1393).
heuristic(pune, madurai, 1062).
heuristic(pune, shillong, 2018).
heuristic(pune, calcutta, 1578).
heuristic(pune, delhi, 1177).
heuristic(pune, cochin, 988).
heuristic(pune, lucknow, 1178).
heuristic(pune, bangalore, 736).
heuristic(pune, indore, 512).
heuristic(pune, patna, 1406).
heuristic(pune, baroda, 428).
heuristic(pune, bhopal, 644).
heuristic(pune, meerut, 1229).
heuristic(pune, coimbatore, 900).
heuristic(pune, panjim, 337).
heuristic(pune, jaipur, 955).
heuristic(pune, jullundur, 1436).
heuristic(pune, imphal, 2191).
heuristic(kanpur, trivandrum, 2032).
heuristic(kanpur, nagpur, 604).
heuristic(kanpur, varanasi, 293).
heuristic(kanpur, jamshedpur, 720).
heuristic(kanpur, agartala, 1142).
heuristic(kanpur, vishakapatnam, 1020).
heuristic(kanpur, asansol, 737).
heuristic(kanpur, gwalior, 216).
heuristic(kanpur, surat, 963).
heuristic(kanpur, ranchi, 610).
heuristic(kanpur, nasik, 982).
heuristic(kanpur, ahmedabad, 872).
heuristic(kanpur, madras, 1491).
heuristic(kanpur, calicut, 1758).
heuristic(kanpur, kolhapur, 1256).
heuristic(kanpur, amritsar, 784).
heuristic(kanpur, vijayawada, 1108).
heuristic(kanpur, bombay, 1122).
heuristic(kanpur, hubli, 1348).
heuristic(kanpur, bhubaneshwar, 886).
heuristic(kanpur, chandigarh, 590).
heuristic(kanpur, agra, 245).
heuristic(kanpur, allahabad, 189).
heuristic(kanpur, jabalpur, 368).
heuristic(kanpur, hyderabad, 1027).
heuristic(kanpur, shimla, 603).
heuristic(kanpur, pondicherry, 1618).
heuristic(kanpur, pune, 1106).
heuristic(kanpur, kanpur, 0).
heuristic(kanpur, ludhiana, 661).
heuristic(kanpur, madurai, 1855).
heuristic(kanpur, shillong, 1161).
heuristic(kanpur, calcutta, 921).
heuristic(kanpur, delhi, 392).
heuristic(kanpur, cochin, 1886).
heuristic(kanpur, lucknow, 75).
heuristic(kanpur, bangalore, 1528).
heuristic(kanpur, indore, 615).
heuristic(kanpur, patna, 490).
heuristic(kanpur, baroda, 859).
heuristic(kanpur, bhopal, 462).
heuristic(kanpur, meerut, 383).
heuristic(kanpur, coimbatore, 1755).
heuristic(kanpur, panjim, 1394).
heuristic(kanpur, jaipur, 455).
heuristic(kanpur, jullundur, 714).
heuristic(kanpur, imphal, 1379).
heuristic(ludhiana, trivandrum, 2498).
heuristic(ludhiana, nagpur, 1133).
heuristic(ludhiana, varanasi, 935).
heuristic(ludhiana, jamshedpur, 1366).
heuristic(ludhiana, agartala, 1715).
heuristic(ludhiana, vishakapatnam, 1649).
heuristic(ludhiana, asansol, 1361).
heuristic(ludhiana, gwalior, 569).
heuristic(ludhiana, surat, 1123).
heuristic(ludhiana, ranchi, 1258).
heuristic(ludhiana, nasik, 1232).
heuristic(ludhiana, ahmedabad, 934).
heuristic(ludhiana, madras, 2037).
heuristic(ludhiana, calicut, 2187).
heuristic(ludhiana, kolhapur, 1591).
heuristic(ludhiana, amritsar, 124).
heuristic(ludhiana, vijayawada, 1675).
heuristic(ludhiana, bombay, 1350).
heuristic(ludhiana, hubli, 1732).
heuristic(ludhiana, bhubaneshwar, 1546).
heuristic(ludhiana, chandigarh, 90).
heuristic(ludhiana, agra, 465).
heuristic(ludhiana, allahabad, 846).
heuristic(ludhiana, jabalpur, 952).
heuristic(ludhiana, hyderabad, 1528).
heuristic(ludhiana, shimla, 127).
heuristic(ludhiana, pondicherry, 2151).
heuristic(ludhiana, pune, 1393).
heuristic(ludhiana, kanpur, 661).
heuristic(ludhiana, ludhiana, 0).
heuristic(ludhiana, madurai, 2347).
heuristic(ludhiana, shillong, 1679).
heuristic(ludhiana, calcutta, 1549).
heuristic(ludhiana, delhi, 285).
heuristic(ludhiana, cochin, 2333).
heuristic(ludhiana, lucknow, 671).
heuristic(ludhiana, bangalore, 2004).
heuristic(ludhiana, indore, 911).
heuristic(ludhiana, patna, 1084).
heuristic(ludhiana, baroda, 993).
heuristic(ludhiana, bhopal, 865).
heuristic(ludhiana, meerut, 278).
heuristic(ludhiana, coimbatore, 2217).
heuristic(ludhiana, panjim, 1728).
heuristic(ludhiana, jaipur, 444).
heuristic(ludhiana, jullundur, 54).
heuristic(ludhiana, imphal, 1903).
heuristic(madurai, trivandrum, 205).
heuristic(madurai, nagpur, 1254).
heuristic(madurai, varanasi, 1789).
heuristic(madurai, jamshedpur, 1673).
heuristic(madurai, agartala, 2086).
heuristic(madurai, vishakapatnam, 1025).
heuristic(madurai, asansol, 1798).
heuristic(madurai, gwalior, 1814).
heuristic(madurai, surat, 1377).
heuristic(madurai, ranchi, 1679).
heuristic(madurai, nasik, 1214).
heuristic(madurai, ahmedabad, 1576).
heuristic(madurai, madras, 419).
heuristic(madurai, calicut, 296).
heuristic(madurai, kolhapur, 862).
heuristic(madurai, amritsar, 2440).
heuristic(madurai, vijayawada, 782).
heuristic(madurai, bombay, 1165).
heuristic(madurai, hubli, 688).
heuristic(madurai, bhubaneshwar, 1420).
heuristic(madurai, chandigarh, 2321).
heuristic(madurai, agra, 1921).
heuristic(madurai, allahabad, 1771).
heuristic(madurai, jabalpur, 1487).
heuristic(madurai, hyderabad, 832).
heuristic(madurai, shimla, 2360).
heuristic(madurai, pondicherry, 288).
heuristic(madurai, pune, 1062).
heuristic(madurai, kanpur, 1855).
heuristic(madurai, ludhiana, 2347).
heuristic(madurai, madurai, 0).
heuristic(madurai, shillong, 2270).
heuristic(madurai, calcutta, 1782).
heuristic(madurai, delhi, 2086).
heuristic(madurai, cochin, 204).
heuristic(madurai, lucknow, 1908).
heuristic(madurai, bangalore, 344).
heuristic(madurai, indore, 1445).
heuristic(madurai, patna, 1897).
heuristic(madurai, baroda, 1476).
heuristic(madurai, bhopal, 1487).
heuristic(madurai, meerut, 2123).
heuristic(madurai, coimbatore, 176).
heuristic(madurai, panjim, 776).
heuristic(madurai, jaipur, 1907).
heuristic(madurai, jullundur, 2397).
heuristic(madurai, imphal, 2357).
heuristic(shillong, trivandrum, 2476).
heuristic(shillong, nagpur, 1398).
heuristic(shillong, varanasi, 897).
heuristic(shillong, jamshedpur, 655).
heuristic(shillong, agartala, 204).
heuristic(shillong, vishakapatnam, 1256).
heuristic(shillong, asansol, 541).
heuristic(shillong, gwalior, 1375).
heuristic(shillong, surat, 2007).
heuristic(shillong, ranchi, 712).
heuristic(shillong, nasik, 1957).
heuristic(shillong, ahmedabad, 1980).
heuristic(shillong, madras, 1852).
heuristic(shillong, calicut, 2328).
heuristic(shillong, kolhapur, 2080).
heuristic(shillong, amritsar, 1793).
heuristic(shillong, vijayawada, 1543).
heuristic(shillong, bombay, 2086).
heuristic(shillong, hubli, 2083).
heuristic(shillong, bhubaneshwar, 856).
heuristic(shillong, chandigarh, 1589).
heuristic(shillong, agra, 1396).
heuristic(shillong, allahabad, 1010).
heuristic(shillong, jabalpur, 1240).
heuristic(shillong, hyderabad, 1660).
heuristic(shillong, shimla, 1567).
heuristic(shillong, pondicherry, 1982).
heuristic(shillong, pune, 2018).
heuristic(shillong, kanpur, 1161).
heuristic(shillong, ludhiana, 1679).
heuristic(shillong, madurai, 2270).
heuristic(shillong, shillong, 0).
heuristic(shillong, calcutta, 491).
heuristic(shillong, delhi, 1492).
heuristic(shillong, cochin, 2398).
heuristic(shillong, lucknow, 1102).
heuristic(shillong, bangalore, 2053).
heuristic(shillong, indore, 1659).
heuristic(shillong, patna, 678).
heuristic(shillong, baroda, 1937).
heuristic(shillong, bhopal, 1490).
heuristic(shillong, meerut, 1453).
heuristic(shillong, coimbatore, 2259).
heuristic(shillong, panjim, 2189).
heuristic(shillong, jaipur, 1614).
heuristic(shillong, jullundur, 1719).
heuristic(shillong, imphal, 224).
heuristic(calcutta, trivandrum, 1987).
heuristic(calcutta, nagpur, 972).
heuristic(calcutta, varanasi, 628).
heuristic(calcutta, jamshedpur, 224).
heuristic(calcutta, agartala, 330).
heuristic(calcutta, vishakapatnam, 765).
heuristic(calcutta, asansol, 189).
heuristic(calcutta, gwalior, 1109).
heuristic(calcutta, surat, 1613).
heuristic(calcutta, ranchi, 325).
heuristic(calcutta, nasik, 1538).
heuristic(calcutta, ahmedabad, 1622).
heuristic(calcutta, madras, 1364).
heuristic(calcutta, calicut, 1837).
heuristic(calcutta, kolhapur, 1618).
heuristic(calcutta, amritsar, 1673).
heuristic(calcutta, vijayawada, 1054).
heuristic(calcutta, bombay, 1657).
heuristic(calcutta, hubli, 1607).
heuristic(calcutta, bhubaneshwar, 365).
heuristic(calcutta, chandigarh, 1466).
heuristic(calcutta, agra, 1164).
heuristic(calcutta, allahabad, 736).
heuristic(calcutta, jabalpur, 866).
heuristic(calcutta, hyderabad, 1184).
heuristic(calcutta, shimla, 1461).
heuristic(calcutta, pondicherry, 1494).
heuristic(calcutta, pune, 1578).
heuristic(calcutta, kanpur, 921).
heuristic(calcutta, ludhiana, 1549).
heuristic(calcutta, madurai, 1782).
heuristic(calcutta, shillong, 491).
heuristic(calcutta, calcutta, 0).
heuristic(calcutta, delhi, 1305).
heuristic(calcutta, cochin, 1908).
heuristic(calcutta, lucknow, 888).
heuristic(calcutta, bangalore, 1563).
heuristic(calcutta, indore, 1285).
heuristic(calcutta, patna, 471).
heuristic(calcutta, baroda, 1562).
heuristic(calcutta, bhopal, 1126).
heuristic(calcutta, meerut, 1284).
heuristic(calcutta, coimbatore, 1769).
heuristic(calcutta, panjim, 1720).
heuristic(calcutta, jaipur, 1360).
heuristic(calcutta, jullundur, 1598).
heuristic(calcutta, imphal, 621).
heuristic(delhi, trivandrum, 2244).
heuristic(delhi, nagpur, 855).
heuristic(delhi, varanasi, 680).
heuristic(delhi, jamshedpur, 1110).
heuristic(delhi, agartala, 1502).
heuristic(delhi, vishakapatnam, 1364).
heuristic(delhi, asansol, 1119).
heuristic(delhi, gwalior, 285).
heuristic(delhi, surat, 940).
heuristic(delhi, ranchi, 1000).
heuristic(delhi, nasik, 1023).
heuristic(delhi, ahmedabad, 778).
heuristic(delhi, madras, 1762).
heuristic(delhi, calicut, 1941).
heuristic(delhi, kolhapur, 1365).
heuristic(delhi, amritsar, 403).
heuristic(delhi, vijayawada, 1395).
heuristic(delhi, bombay, 1153).
heuristic(delhi, hubli, 1493).
heuristic(delhi, bhubaneshwar, 1273).
heuristic(delhi, chandigarh, 238).
heuristic(delhi, agra, 180).
heuristic(delhi, allahabad, 580).
heuristic(delhi, jabalpur, 667).
heuristic(delhi, hyderabad, 1259).
heuristic(delhi, shimla, 275).
heuristic(delhi, pondicherry, 1879).
heuristic(delhi, pune, 1177).
heuristic(delhi, kanpur, 392).
heuristic(delhi, ludhiana, 285).
heuristic(delhi, madurai, 2086).
heuristic(delhi, shillong, 1492).
heuristic(delhi, calcutta, 1305).
heuristic(delhi, delhi, 0).
heuristic(delhi, cochin, 2083).
heuristic(delhi, lucknow, 417).
heuristic(delhi, bangalore, 1745).
heuristic(delhi, indore, 673).
heuristic(delhi, patna, 854).
heuristic(delhi, baroda, 813).
heuristic(delhi, bhopal, 599).
heuristic(delhi, meerut, 61).
heuristic(delhi, coimbatore, 1962).
heuristic(delhi, panjim, 1504).
heuristic(delhi, jaipur, 238).
heuristic(delhi, jullundur, 339).
heuristic(delhi, imphal, 1715).
heuristic(cochin, trivandrum, 180).
heuristic(cochin, nagpur, 1283).
heuristic(cochin, varanasi, 1852).
heuristic(cochin, jamshedpur, 1780).
heuristic(cochin, agartala, 2221).
heuristic(cochin, vishakapatnam, 1143).
heuristic(cochin, asansol, 1906).
heuristic(cochin, gwalior, 1822).
heuristic(cochin, surat, 1305).
heuristic(cochin, ranchi, 1775).
heuristic(cochin, nasik, 1149).
heuristic(cochin, ahmedabad, 1509).
heuristic(cochin, madras, 556).
heuristic(cochin, calicut, 154).
heuristic(cochin, kolhapur, 781).
heuristic(cochin, amritsar, 2418).
heuristic(cochin, vijayawada, 871).
heuristic(cochin, bombay, 1079).
heuristic(cochin, hubli, 615).
heuristic(cochin, bhubaneshwar, 1543).
heuristic(cochin, chandigarh, 2314).
heuristic(cochin, agra, 1927).
heuristic(cochin, allahabad, 1822).
heuristic(cochin, jabalpur, 1523).
heuristic(cochin, hyderabad, 862).
heuristic(cochin, shimla, 2357).
heuristic(cochin, pondicherry, 444).
heuristic(cochin, pune, 988).
heuristic(cochin, kanpur, 1886).
heuristic(cochin, ludhiana, 2333).
heuristic(cochin, madurai, 204).
heuristic(cochin, shillong, 2398).
heuristic(cochin, calcutta, 1908).
heuristic(cochin, delhi, 2083).
heuristic(cochin, cochin, 0).
heuristic(cochin, lucknow, 1945).
heuristic(cochin, bangalore, 366).
heuristic(cochin, indore, 1422).
heuristic(cochin, patna, 1980).
heuristic(cochin, baroda, 1414).
heuristic(cochin, bhopal, 1487).
heuristic(cochin, meerut, 2124).
heuristic(cochin, coimbatore, 141).
heuristic(cochin, panjim, 671).
heuristic(cochin, jaipur, 1889).
heuristic(cochin, jullundur, 2381).
heuristic(cochin, imphal, 2498).
heuristic(lucknow, trivandrum, 2087).
heuristic(lucknow, nagpur, 662).
heuristic(lucknow, varanasi, 265).
heuristic(lucknow, jamshedpur, 696).
heuristic(lucknow, agartala, 1093).
heuristic(lucknow, vishakapatnam, 1046).
heuristic(lucknow, asansol, 701).
heuristic(lucknow, gwalior, 284).
heuristic(lucknow, surat, 1038).
heuristic(lucknow, ranchi, 588).
heuristic(lucknow, nasik, 1056).
heuristic(lucknow, ahmedabad, 946).
heuristic(lucknow, madras, 1537).
heuristic(lucknow, calicut, 1818).
heuristic(lucknow, kolhapur, 1326).
heuristic(lucknow, amritsar, 795).
heuristic(lucknow, vijayawada, 1152).
heuristic(lucknow, bombay, 1196).
heuristic(lucknow, hubli, 1414).
heuristic(lucknow, bhubaneshwar, 883).
heuristic(lucknow, chandigarh, 594).
heuristic(lucknow, agra, 294).
heuristic(lucknow, allahabad, 181).
heuristic(lucknow, jabalpur, 422).
heuristic(lucknow, hyderabad, 1084).
heuristic(lucknow, shimla, 600).
heuristic(lucknow, pondicherry, 1665).
heuristic(lucknow, pune, 1178).
heuristic(lucknow, kanpur, 75).
heuristic(lucknow, ludhiana, 671).
heuristic(lucknow, madurai, 1908).
heuristic(lucknow, shillong, 1102).
heuristic(lucknow, calcutta, 888).
heuristic(lucknow, delhi, 417).
heuristic(lucknow, cochin, 1945).
heuristic(lucknow, lucknow, 0).
heuristic(lucknow, bangalore, 1584).
heuristic(lucknow, indore, 690).
heuristic(lucknow, patna, 441).
heuristic(lucknow, baroda, 934).
heuristic(lucknow, bhopal, 535).
heuristic(lucknow, meerut, 398).
heuristic(lucknow, coimbatore, 1812).
heuristic(lucknow, panjim, 1463).
heuristic(lucknow, jaipur, 512).
heuristic(lucknow, jullundur, 722).
heuristic(lucknow, imphal, 1322).
heuristic(bangalore, trivandrum, 504).
heuristic(bangalore, nagpur, 924).
heuristic(bangalore, varanasi, 1486).
heuristic(bangalore, jamshedpur, 1424).
heuristic(bangalore, agartala, 1883).
heuristic(bangalore, vishakapatnam, 800).
heuristic(bangalore, asansol, 1550).
heuristic(bangalore, gwalior, 1476).
heuristic(bangalore, surat, 1047).
heuristic(bangalore, ranchi, 1413).
heuristic(bangalore, nasik, 881).
heuristic(bangalore, ahmedabad, 1241).
heuristic(bangalore, madras, 288).
heuristic(bangalore, calicut, 275).
heuristic(bangalore, kolhapur, 549).
heuristic(bangalore, amritsar, 2097).
heuristic(bangalore, vijayawada, 513).
heuristic(bangalore, bombay, 847).
heuristic(bangalore, hubli, 377).
heuristic(bangalore, bhubaneshwar, 1198).
heuristic(bangalore, chandigarh, 1980).
heuristic(bangalore, agra, 1582).
heuristic(bangalore, allahabad, 1458).
heuristic(bangalore, jabalpur, 1162).
heuristic(bangalore, hyderabad, 501).
heuristic(bangalore, shimla, 2019).
heuristic(bangalore, pondicherry, 265).
heuristic(bangalore, pune, 736).
heuristic(bangalore, kanpur, 1528).
heuristic(bangalore, ludhiana, 2004).
heuristic(bangalore, madurai, 344).
heuristic(bangalore, shillong, 2053).
heuristic(bangalore, calcutta, 1563).
heuristic(bangalore, delhi, 1745).
heuristic(bangalore, cochin, 366).
heuristic(bangalore, lucknow, 1584).
heuristic(bangalore, bangalore, 0).
heuristic(bangalore, indore, 1101).
heuristic(bangalore, patna, 1614).
heuristic(bangalore, baroda, 1140).
heuristic(bangalore, bhopal, 1146).
heuristic(bangalore, meerut, 1783).
heuristic(bangalore, coimbatore, 229).
heuristic(bangalore, panjim, 494).
heuristic(bangalore, jaipur, 1564).
heuristic(bangalore, jullundur, 2054).
heuristic(bangalore, imphal, 2165).
heuristic(indore, trivandrum, 1589).
heuristic(indore, nagpur, 377).
heuristic(indore, varanasi, 779).
heuristic(indore, jamshedpur, 1062).
heuristic(indore, agartala, 1582).
heuristic(indore, vishakapatnam, 951).
heuristic(indore, asansol, 1142).
heuristic(indore, gwalior, 455).
heuristic(indore, surat, 357).
heuristic(indore, ranchi, 971).
heuristic(indore, nasik, 371).
heuristic(indore, ahmedabad, 340).
heuristic(indore, madras, 1172).
heuristic(indore, calicut, 1276).
heuristic(indore, kolhapur, 692).
heuristic(indore, amritsar, 997).
heuristic(indore, vijayawada, 855).
heuristic(indore, bombay, 511).
heuristic(indore, hubli, 823).
heuristic(indore, bhubaneshwar, 1067).
heuristic(indore, chandigarh, 897).
heuristic(indore, agra, 542).
heuristic(indore, allahabad, 680).
heuristic(indore, jabalpur, 423).
heuristic(indore, hyderabad, 655).
heuristic(indore, shimla, 942).
heuristic(indore, pondicherry, 1272).
heuristic(indore, pune, 512).
heuristic(indore, kanpur, 615).
heuristic(indore, ludhiana, 911).
heuristic(indore, madurai, 1445).
heuristic(indore, shillong, 1659).
heuristic(indore, calcutta, 1285).
heuristic(indore, delhi, 673).
heuristic(indore, cochin, 1422).
heuristic(indore, lucknow, 690).
heuristic(indore, bangalore, 1101).
heuristic(indore, indore, 0).
heuristic(indore, patna, 996).
heuristic(indore, baroda, 279).
heuristic(indore, bhopal, 170).
heuristic(indore, meerut, 722).
heuristic(indore, coimbatore, 1308).
heuristic(indore, panjim, 832).
heuristic(indore, jaipur, 467).
heuristic(indore, jullundur, 959).
heuristic(indore, imphal, 1857).
heuristic(patna, trivandrum, 2095).
heuristic(patna, nagpur, 793).
heuristic(patna, varanasi, 220).
heuristic(patna, jamshedpur, 331).
heuristic(patna, agartala, 652).
heuristic(patna, vishakapatnam, 904).
heuristic(patna, asansol, 283).
heuristic(patna, gwalior, 700).
heuristic(patna, surat, 1351).
heuristic(patna, ranchi, 253).
heuristic(patna, nasik, 1321).
heuristic(patna, ahmedabad, 1307).
heuristic(patna, madras, 1489).
heuristic(patna, calicut, 1877).
heuristic(patna, kolhapur, 1504).
heuristic(patna, amritsar, 1206).
heuristic(patna, vijayawada, 1116).
heuristic(patna, bombay, 1456).
heuristic(patna, hubli, 1546).
heuristic(patna, bhubaneshwar, 596).
heuristic(patna, chandigarh, 999).
heuristic(patna, agra, 732).
heuristic(patna, allahabad, 332).
heuristic(patna, jabalpur, 593).
heuristic(patna, hyderabad, 1146).
heuristic(patna, shimla, 992).
heuristic(patna, pondicherry, 1624).
heuristic(patna, pune, 1406).
heuristic(patna, kanpur, 490).
heuristic(patna, ludhiana, 1084).
heuristic(patna, madurai, 1897).
heuristic(patna, shillong, 678).
heuristic(patna, calcutta, 471).
heuristic(patna, delhi, 854).
heuristic(patna, cochin, 1980).
heuristic(patna, lucknow, 441).
heuristic(patna, bangalore, 1614).
heuristic(patna, indore, 996).
heuristic(patna, patna, 0).
heuristic(patna, baroda, 1271).
heuristic(patna, bhopal, 826).
heuristic(patna, meerut, 826).
heuristic(patna, coimbatore, 1840).
heuristic(patna, panjim, 1629).
heuristic(patna, jaipur, 945).
heuristic(patna, jullundur, 1131).
heuristic(patna, imphal, 892).
heuristic(baroda, trivandrum, 1591).
heuristic(baroda, nagpur, 625).
heuristic(baroda, varanasi, 1052).
heuristic(baroda, jamshedpur, 1340).
heuristic(baroda, agartala, 1861).
heuristic(baroda, vishakapatnam, 1169).
heuristic(baroda, asansol, 1421).
heuristic(baroda, gwalior, 669).
heuristic(baroda, surat, 129).
heuristic(baroda, ranchi, 1250).
heuristic(baroda, nasik, 265).
heuristic(baroda, ahmedabad, 103).
heuristic(baroda, madras, 1273).
heuristic(baroda, calicut, 1261).
heuristic(baroda, kolhapur, 635).
heuristic(baroda, amritsar, 1052).
heuristic(baroda, vijayawada, 1016).
heuristic(baroda, bombay, 361).
heuristic(baroda, hubli, 800).
heuristic(baroda, bhubaneshwar, 1330).
heuristic(baroda, chandigarh, 1004).
heuristic(baroda, agra, 729).
heuristic(baroda, allahabad, 948).
heuristic(baroda, jabalpur, 702).
heuristic(baroda, hyderabad, 780).
heuristic(baroda, shimla, 1056).
heuristic(baroda, pondicherry, 1352).
heuristic(baroda, pune, 428).
heuristic(baroda, kanpur, 859).
heuristic(baroda, ludhiana, 993).
heuristic(baroda, madurai, 1476).
heuristic(baroda, shillong, 1937).
heuristic(baroda, calcutta, 1562).
heuristic(baroda, delhi, 813).
heuristic(baroda, cochin, 1414).
heuristic(baroda, lucknow, 934).
heuristic(baroda, bangalore, 1140).
heuristic(baroda, indore, 279).
heuristic(baroda, patna, 1271).
heuristic(baroda, baroda, 0).
heuristic(baroda, bhopal, 447).
heuristic(baroda, meerut, 871).
heuristic(baroda, coimbatore, 1320).
heuristic(baroda, panjim, 762).
heuristic(baroda, jaipur, 577).
heuristic(baroda, jullundur, 1032).
heuristic(baroda, imphal, 2136).
heuristic(bhopal, trivandrum, 1646).
heuristic(bhopal, nagpur, 292).
heuristic(bhopal, varanasi, 609).
heuristic(bhopal, jamshedpur, 902).
heuristic(bhopal, agartala, 1417).
heuristic(bhopal, vishakapatnam, 867).
heuristic(bhopal, asansol, 977).
heuristic(bhopal, gwalior, 338).
heuristic(bhopal, surat, 526).
heuristic(bhopal, ranchi, 808).
heuristic(bhopal, nasik, 522).
heuristic(bhopal, ahmedabad, 497).
heuristic(bhopal, madras, 1175).
heuristic(bhopal, calicut, 1348).
heuristic(bhopal, kolhapur, 803).
heuristic(bhopal, amritsar, 966).
heuristic(bhopal, vijayawada, 825).
heuristic(bhopal, bombay, 662).
heuristic(bhopal, hubli, 911).
heuristic(bhopal, bhubaneshwar, 930).
heuristic(bhopal, chandigarh, 835).
heuristic(bhopal, agra, 440).
heuristic(bhopal, allahabad, 511).
heuristic(bhopal, jabalpur, 260).
heuristic(bhopal, hyderabad, 664).
heuristic(bhopal, shimla, 874).
heuristic(bhopal, pondicherry, 1286).
heuristic(bhopal, pune, 644).
heuristic(bhopal, kanpur, 462).
heuristic(bhopal, ludhiana, 865).
heuristic(bhopal, madurai, 1487).
heuristic(bhopal, shillong, 1490).
heuristic(bhopal, calcutta, 1126).
heuristic(bhopal, delhi, 599).
heuristic(bhopal, cochin, 1487).
heuristic(bhopal, lucknow, 535).
heuristic(bhopal, bangalore, 1146).
heuristic(bhopal, indore, 170).
heuristic(bhopal, patna, 826).
heuristic(bhopal, baroda, 447).
heuristic(bhopal, bhopal, 0).
heuristic(bhopal, meerut, 638).
heuristic(bhopal, coimbatore, 1364).
heuristic(bhopal, panjim, 943).
heuristic(bhopal, jaipur, 438).
heuristic(bhopal, jullundur, 916).
heuristic(bhopal, imphal, 1689).
heuristic(meerut, trivandrum, 2284).
heuristic(meerut, nagpur, 884).
heuristic(meerut, varanasi, 662).
heuristic(meerut, jamshedpur, 1094).
heuristic(meerut, agartala, 1470).
heuristic(meerut, vishakapatnam, 1378).
heuristic(meerut, asansol, 1096).
heuristic(meerut, gwalior, 312).
heuristic(meerut, surat, 997).
heuristic(meerut, ranchi, 985).
heuristic(meerut, nasik, 1076).
heuristic(meerut, ahmedabad, 838).
heuristic(meerut, madras, 1793).
heuristic(meerut, calicut, 1984).
heuristic(meerut, kolhapur, 1414).
heuristic(meerut, amritsar, 402).
heuristic(meerut, vijayawada, 1422).
heuristic(meerut, bombay, 1207).
heuristic(meerut, hubli, 1540).
heuristic(meerut, bhubaneshwar, 1268).
heuristic(meerut, chandigarh, 214).
heuristic(meerut, agra, 203).
heuristic(meerut, allahabad, 569).
heuristic(meerut, jabalpur, 686).
heuristic(meerut, hyderabad, 1294).
heuristic(meerut, shimla, 241).
heuristic(meerut, pondicherry, 1911).
heuristic(meerut, pune, 1229).
heuristic(meerut, kanpur, 383).
heuristic(meerut, ludhiana, 278).
heuristic(meerut, madurai, 2123).
heuristic(meerut, shillong, 1453).
heuristic(meerut, calcutta, 1284).
heuristic(meerut, delhi, 61).
heuristic(meerut, cochin, 2124).
heuristic(meerut, lucknow, 398).
heuristic(meerut, bangalore, 1783).
heuristic(meerut, indore, 722).
heuristic(meerut, patna, 826).
heuristic(meerut, baroda, 871).
heuristic(meerut, bhopal, 638).
heuristic(meerut, meerut, 0).
heuristic(meerut, coimbatore, 2002).
heuristic(meerut, panjim, 1554).
heuristic(meerut, jaipur, 298).
heuristic(meerut, jullundur, 332).
heuristic(meerut, imphal, 1677).
heuristic(coimbatore, trivandrum, 282).
heuristic(coimbatore, nagpur, 1151).
heuristic(coimbatore, varanasi, 1714).
heuristic(coimbatore, jamshedpur, 1640).
heuristic(coimbatore, agartala, 2083).
heuristic(coimbatore, vishakapatnam, 1004).
heuristic(coimbatore, asansol, 1766).
heuristic(coimbatore, gwalior, 1698).
heuristic(coimbatore, surat, 1216).
heuristic(coimbatore, ranchi, 1634).
heuristic(coimbatore, nasik, 1056).
heuristic(coimbatore, ahmedabad, 1418).
heuristic(coimbatore, madras, 425).
heuristic(coimbatore, calicut, 131).
heuristic(coimbatore, kolhapur, 696).
heuristic(coimbatore, amritsar, 2306).
heuristic(coimbatore, vijayawada, 730).
heuristic(coimbatore, bombay, 999).
heuristic(coimbatore, hubli, 523).
heuristic(coimbatore, bhubaneshwar, 1403).
heuristic(coimbatore, chandigarh, 2196).
heuristic(coimbatore, agra, 1803).
heuristic(coimbatore, allahabad, 1686).
heuristic(coimbatore, jabalpur, 1390).
heuristic(coimbatore, hyderabad, 728).
heuristic(coimbatore, shimla, 2237).
heuristic(coimbatore, pondicherry, 325).
heuristic(coimbatore, pune, 900).
heuristic(coimbatore, kanpur, 1755).
heuristic(coimbatore, ludhiana, 2217).
heuristic(coimbatore, madurai, 176).
heuristic(coimbatore, shillong, 2259).
heuristic(coimbatore, calcutta, 1769).
heuristic(coimbatore, delhi, 1962).
heuristic(coimbatore, cochin, 141).
heuristic(coimbatore, lucknow, 1812).
heuristic(coimbatore, bangalore, 229).
heuristic(coimbatore, indore, 1308).
heuristic(coimbatore, patna, 1840).
heuristic(coimbatore, baroda, 1320).
heuristic(coimbatore, bhopal, 1364).
heuristic(coimbatore, meerut, 2002).
heuristic(coimbatore, coimbatore, 0).
heuristic(coimbatore, panjim, 603).
heuristic(coimbatore, jaipur, 1774).
heuristic(coimbatore, jullundur, 2266).
heuristic(coimbatore, imphal, 2361).
heuristic(panjim, trivandrum, 851).
heuristic(panjim, nagpur, 840).
heuristic(panjim, varanasi, 1451).
heuristic(panjim, jamshedpur, 1534).
heuristic(panjim, agartala, 2050).
heuristic(panjim, vishakapatnam, 1032).
heuristic(panjim, asansol, 1652).
heuristic(panjim, gwalior, 1277).
heuristic(panjim, surat, 643).
heuristic(panjim, ranchi, 1488).
heuristic(panjim, nasik, 501).
heuristic(panjim, ahmedabad, 850).
heuristic(panjim, madras, 744).
heuristic(panjim, calicut, 517).
heuristic(panjim, kolhapur, 141).
heuristic(panjim, amritsar, 1800).
heuristic(panjim, vijayawada, 739).
heuristic(panjim, bombay, 411).
heuristic(panjim, hubli, 140).
heuristic(panjim, bhubaneshwar, 1379).
heuristic(panjim, chandigarh, 1723).
heuristic(panjim, agra, 1371).
heuristic(panjim, allahabad, 1387).
heuristic(panjim, jabalpur, 1069).
heuristic(panjim, hyderabad, 540).
heuristic(panjim, shimla, 1771).
heuristic(panjim, pondicherry, 757).
heuristic(panjim, pune, 337).
heuristic(panjim, kanpur, 1394).
heuristic(panjim, ludhiana, 1728).
heuristic(panjim, madurai, 776).
heuristic(panjim, shillong, 2189).
heuristic(panjim, calcutta, 1720).
heuristic(panjim, delhi, 1504).
heuristic(panjim, cochin, 671).
heuristic(panjim, lucknow, 1463).
heuristic(panjim, bangalore, 494).
heuristic(panjim, indore, 832).
heuristic(panjim, patna, 1629).
heuristic(panjim, baroda, 762).
heuristic(panjim, bhopal, 943).
heuristic(panjim, meerut, 1554).
heuristic(panjim, coimbatore, 603).
heuristic(panjim, panjim, 0).
heuristic(panjim, jaipur, 1287).
heuristic(panjim, jullundur, 1772).
heuristic(panjim, imphal, 2341).
heuristic(jaipur, trivandrum, 2055).
heuristic(jaipur, nagpur, 724).
heuristic(jaipur, varanasi, 740).
heuristic(jaipur, jamshedpur, 1147).
heuristic(jaipur, agartala, 1596).
heuristic(jaipur, vishakapatnam, 1280).
heuristic(jaipur, asansol, 1181).
heuristic(jaipur, gwalior, 251).
heuristic(jaipur, surat, 704).
heuristic(jaipur, ranchi, 1039).
heuristic(jaipur, nasik, 797).
heuristic(jaipur, ahmedabad, 540).
heuristic(jaipur, madras, 1611).
heuristic(jaipur, calicut, 1743).
heuristic(jaipur, kolhapur, 1149).
heuristic(jaipur, amritsar, 533).
heuristic(jaipur, vijayawada, 1263).
heuristic(jaipur, bombay, 922).
heuristic(jaipur, hubli, 1288).
heuristic(jaipur, bhubaneshwar, 1261).
heuristic(jaipur, chandigarh, 436).
heuristic(jaipur, agra, 222).
heuristic(jaipur, allahabad, 627).
heuristic(jaipur, jabalpur, 592).
heuristic(jaipur, hyderabad, 1097).
heuristic(jaipur, shimla, 486).
heuristic(jaipur, pondicherry, 1720).
heuristic(jaipur, pune, 955).
heuristic(jaipur, kanpur, 455).
heuristic(jaipur, ludhiana, 444).
heuristic(jaipur, madurai, 1907).
heuristic(jaipur, shillong, 1614).
heuristic(jaipur, calcutta, 1360).
heuristic(jaipur, delhi, 238).
heuristic(jaipur, cochin, 1889).
heuristic(jaipur, lucknow, 512).
heuristic(jaipur, bangalore, 1564).
heuristic(jaipur, indore, 467).
heuristic(jaipur, patna, 945).
heuristic(jaipur, baroda, 577).
heuristic(jaipur, bhopal, 438).
heuristic(jaipur, meerut, 298).
heuristic(jaipur, coimbatore, 1774).
heuristic(jaipur, panjim, 1287).
heuristic(jaipur, jaipur, 0).
heuristic(jaipur, jullundur, 492).
heuristic(jaipur, imphal, 1833).
heuristic(jullundur, trivandrum, 2547).
heuristic(jullundur, nagpur, 1186).
heuristic(jullundur, varanasi, 986).
heuristic(jullundur, jamshedpur, 1416).
heuristic(jullundur, agartala, 1758).
heuristic(jullundur, vishakapatnam, 1703).
heuristic(jullundur, asansol, 1409).
heuristic(jullundur, gwalior, 623).
heuristic(jullundur, surat, 1161).
heuristic(jullundur, ranchi, 1309).
heuristic(jullundur, nasik, 1274).
heuristic(jullundur, ahmedabad, 970).
heuristic(jullundur, madras, 2089).
heuristic(jullundur, calicut, 2235).
heuristic(jullundur, kolhapur, 1635).
heuristic(jullundur, amritsar, 75).
heuristic(jullundur, vijayawada, 1728).
heuristic(jullundur, bombay, 1391).
heuristic(jullundur, hubli, 1778).
heuristic(jullundur, bhubaneshwar, 1599).
heuristic(jullundur, chandigarh, 132).
heuristic(jullundur, agra, 519).
heuristic(jullundur, allahabad, 898).
heuristic(jullundur, jabalpur, 1006).
heuristic(jullundur, hyderabad, 1580).
heuristic(jullundur, shimla, 154).
heuristic(jullundur, pondicherry, 2203).
heuristic(jullundur, pune, 1436).
heuristic(jullundur, kanpur, 714).
heuristic(jullundur, ludhiana, 54).
heuristic(jullundur, madurai, 2397).
heuristic(jullundur, shillong, 1719).
heuristic(jullundur, calcutta, 1598).
heuristic(jullundur, delhi, 339).
heuristic(jullundur, cochin, 2381).
heuristic(jullundur, lucknow, 722).
heuristic(jullundur, bangalore, 2054).
heuristic(jullundur, indore, 959).
heuristic(jullundur, patna, 1131).
heuristic(jullundur, baroda, 1032).
heuristic(jullundur, bhopal, 916).
heuristic(jullundur, meerut, 332).
heuristic(jullundur, coimbatore, 2266).
heuristic(jullundur, panjim, 1772).
heuristic(jullundur, jaipur, 492).
heuristic(jullundur, jullundur, 0).
heuristic(jullundur, imphal, 1942).
heuristic(imphal, trivandrum, 2561).
heuristic(imphal, nagpur, 1576).
heuristic(imphal, varanasi, 1108).
heuristic(imphal, jamshedpur, 820).
heuristic(imphal, agartala, 291).
heuristic(imphal, vishakapatnam, 1366).
heuristic(imphal, asansol, 719).
heuristic(imphal, gwalior, 1591).
heuristic(imphal, surat, 2200).
heuristic(imphal, ranchi, 893).
heuristic(imphal, nasik, 2141).
heuristic(imphal, ahmedabad, 2183).
heuristic(imphal, madras, 1945).
heuristic(imphal, calicut, 2439).
heuristic(imphal, kolhapur, 2238).
heuristic(imphal, amritsar, 2016).
heuristic(imphal, vijayawada, 1664).
heuristic(imphal, bombay, 2265).
heuristic(imphal, hubli, 2228).
heuristic(imphal, bhubaneshwar, 974).
heuristic(imphal, chandigarh, 1813).
heuristic(imphal, agra, 1616).
heuristic(imphal, allahabad, 1222).
heuristic(imphal, jabalpur, 1435).
heuristic(imphal, hyderabad, 1804).
heuristic(imphal, shimla, 1790).
heuristic(imphal, pondicherry, 2069).
heuristic(imphal, pune, 2191).
heuristic(imphal, kanpur, 1379).
heuristic(imphal, ludhiana, 1903).
heuristic(imphal, madurai, 2357).
heuristic(imphal, shillong, 224).
heuristic(imphal, calcutta, 621).
heuristic(imphal, delhi, 1715).
heuristic(imphal, cochin, 2498).
heuristic(imphal, lucknow, 1322).
heuristic(imphal, bangalore, 2165).
heuristic(imphal, indore, 1857).
heuristic(imphal, patna, 892).
heuristic(imphal, baroda, 2136).
heuristic(imphal, bhopal, 1689).
heuristic(imphal, meerut, 1677).
heuristic(imphal, coimbatore, 2361).
heuristic(imphal, panjim, 2341).
heuristic(imphal, jaipur, 1833).
heuristic(imphal, jullundur, 1942).
heuristic(imphal, imphal, 0).
